### ISSUE TITLE
Bringing down a container when a supervised process crashes.

### ISSUE THREAD

**Issue by smebberson** [just-containers/s6-overlay#101]
I wanted to bring up the script that we all came up with in that [thread](https://github.com/just-containers/s6-overlay/issues/41#issuecomment-95461028), that is supposed to bring a container down when a server crashes.

```
#!/usr/bin/execlineb -S0
if -n { s6-test $# -ne 0 }
if -n { s6-test ${1} -eq 256 }

s6-svscanctl -t /var/run/s6/services
```

In doing some testing recently, we found that it doesn't actually work. If you take a look at the first line of the script (after the shebang) it reads if the number of arguments passed to the `./finish` script is not equal to `0` then stop the `./finish` script executing (resulting in the service being restarted). In the instance a script crashes, I would expect their to be a non-zero argument passed to the `./finish` script. Therefore the script is not doing it's job. We've rewritten it with a detailed explanation (we're not strong in execline). Can you guys please help us validate it? We've run it, and it actually works when running it.

## Rewrite

Desired outcome is to stop the container, if the supervised process exists non-zero (i.e. fails).
If the container was signaled to stop, this script should do nothing.

```
#!/usr/bin/execlineb -S0
if -n { s6-test ${1} -eq 0 }
if -n { s6-test ${1} -eq 256 }

s6-svscanctl -t /var/run/s6/services
```

## Line 1

`s6-test ${1} -eq 0`
- If script is run and the first argument is `0`, `s6-test` will exit `0`.
- If script is run and the first argument is not `0`, `s6-test` will exit `1`.
- Explained: if the supervised process exited non-zero `s6-test` will exit `1`.

`if -n { s6-test ${1} -eq 0 }`
- If `s6-test` exits `0` (`true`), exit `1`.
- If `s6-test` exits `1` (`false`), goto next line. 
- Explained: if the supervised process exited non-zero, goto next line. If the supervised process exited `0`, stop execution of the `./finish` script.

## Line 2

`s6-test ${1} -eq 256`
- If script is run and the first argument is `256`, `s6-test` will exit `0`.
- If script is run and the first argument is not `256`, `s6-test` will exit `1`.
- Explained: if the supervised process was signaled `s6-test` will exit `0`.

`if -n { s6-test ${1} -eq 256 }`
- If `s6-test` exits `0` (`true`), exit `1`.
- If `s6-test` exits `1` (`false`), goto next line.
- Explain: if the supervised process was signalled, stop execution of the `./finish` script. If the supervised process was not signalled, goto next line.

**Comment by glerchundi** [comment]
Hei @smebberson, great explanation! i think `-n` and `-eq` can be rewritten into just `-ne`:

```
#!/usr/bin/execlineb -S0
if { s6-test ${1} -ne 0 }
if { s6-test ${1} -ne 256 }

s6-svscanctl -t /var/run/s6/services
```

WDYT?

**Comment by smebberson** [comment]
@glerchundi, yeah, that works too.

Can you confirm the logic is correct though, in moving away from checking `$#` to checking `${1}` on the first line?

**Comment by glerchundi** [comment]
hi @smebberson,

`if { s6-test $# -ne 0 }` doesn't hurt, is just a sanity check and as far as I know it does nothing because `finish` always will be run with parameters.

`if { s6-test ${1} -ne 0 }` means two things, your process died abnormally or it was signaled by the supervisor. So in this moment you cannot assure why was `./finish` run.

`if { s6-test ${1} -ne 256 }` means that `./finish` was run because process exited.

So in this case, `s6-svscanctl` will be called if your process exited abnormally but was not called by the supervisor. That means that your container will be kept running even if you call it with `docker stop`. Is that what you really want?

**Comment by smebberson** [comment]
@glerchundi, if s6 was signalled (i.e. `docker stop`, or `CTRL+C`) wouldn't s6 bring down the container anyway (i.e. after the `./finish` script has run - it won't restart the service). I didn't think it was the `./finish` scripts responsibility to bring down the container under normal circumstances.

That is why I had `if -n { s6-test ${1} -eq 256 }`, so that if the container was signalled, the `./finish` script would exit without actually firing `s6-svscanctl` command (think s6 would continue bringing down all containers).

**Comment by smebberson** [comment]
@glerchundi, I should clarify the purpose of the script is to bring down the container if the process non-zero exited (as opposed to restart the service which is normal s6 operation).

**Comment by glerchundi** [comment]
> That means that your container will be kept running even if you call it with docker stop. Is that what you really want?

Yep, forget this, you're right.

Just to conclude this, the script would look like this:

```
#!/usr/bin/execlineb -S1
if { s6-test ${1} -ne 0 }
if { s6-test ${1} -ne 256 }

s6-svscanctl -t /var/run/s6/services
```

Can you test it for me? I'm going to modify the README accordingly.

**Comment by smebberson** [comment]
@glerchundi, yep, I can confirm that works! Great.

**Comment by jprjr** [comment]
Hi @smebberson @glerchundi - I've updated the readme. Go ahead and close this, or let me know if I'm ok to close it. Thanks!

**Comment by glerchundi** [comment]
as @smebberson opened it, the ball is in your court

**Comment by smebberson** [comment]
Sorry guys. This all looks great! Thank you.

**Comment by agners** [comment]
This exits the finish script (and thus restarts the service) when the process experience a segmentation fault (e.g. gets terminated by the `SIGSEGV` signal). This seems to contradict what the title of the issue is saying: The goal is to bring down the container if the supervised processes crashes... For that particular case, a more involved script is necessary.

It seems the goal of `if { s6-test ${1} -ne 256 }` is to avoid the `finish` script taking down the service which is in the process of being taken down by the supervisor. The default signal to take down a service is `SIGTERM`.

So I came up with the following extension which excludes SIGTERM (15) but makes sure the container exits if the main process exited by any other signal (such as `SIGSEGV`, `SIGILL` etc.). The second argument passed to the finish script is the signal received by the process.

```
#!/usr/bin/execlineb -S1
if { s6-test ${1} -ne 0 }
ifelse { s6-test ${1} -ne 256 }
  if { s6-test ${2} -ne 15 }
  s6-svscanctl -t /var/run/s6/services
}

s6-svscanctl -t /var/run/s6/services
```

Inspiration from https://github.com/just-containers/s6-overlay/issues/320#issuecomment-772878324
