### ISSUE TITLE
Service init order (services dependencies)

### ISSUE THREAD

**Issue by oscar-martin** [just-containers/s6-overlay#112]
Hi,

I'm starting getting into s6-overlay (not willing to read the whole s6 project yet) but I did not find a way to define services dependencies. Is it s6-rc integrated in this s6-overlay?

If so, how can I make use of it. Otherwise, any hint about how I can use s6-rc stuff in my docker image is welcome.

Thanks!

**Comment by glerchundi** [comment]
@oscar-martin, you can achieve this by using `s6-svwait` like we're already doing [here](https://github.com/just-containers/s6-overlay/blob/master/builder/overlay-rootfs/usr/bin/logutil-newfifo#L12).

First but: Obviously, a better approach would be to use `s6-rc` which among other things handles dependencies graphs effectively.
Second but: `s6-rc` is in its early stages and although `s6-overlay` doesn't support it, it could be the motivation for the second major version.

**Comment by oscar-martin** [comment]
Great! Thanks for the guidance.

**Comment by smebberson** [comment]
@glerchundi, could this perhaps be reopened? I'd love to see `s6-rc` in s6-overlay. I think it would be an awesome combination.

I've started to have a good read of the `s6-rc` website.

I would be keen to start a PR to integrate `s6-rc`, but I wouldn't do that with some design conversations with you guys. I had an s6-based container which I dreamed up myself. I dropped that in an instant when I discovered s6-overlay with all of the extra goodness it has. I know that each of the core contributors to this project could do a better job than I. But I'm willing to help.

Is there any interest in getting this off the ground?

(Perhaps, even another project which takes s6-overlay and mixes in s6-rc so that people can use the s6-overlay image without s6-rc if they don't need service dependancy management?)

**Comment by glerchundi** [comment]
@smebberson @oscar-martin I filled a new issue regarding to integrate `s6-rc` into the overlay.

**Comment by Adirelle** [comment]
I have started a project around s6-rc for containers : https://github.com/Adirelle/s6rc-overlay

It started as a base image for building development images. I extracted the scripts and switched to just-containes/skaware for the binaries. Right now, it is still in an early stage but I plan to use it where I work, so it will eventually work.
