### ISSUE TITLE
fmode permission used on directories when not recursing (fix-attrs.d)

### ISSUE THREAD

**Issue by nigelgbanks** [just-containers/s6-overlay#131]
I think I found an issue with permissions using the **fmode** on directories when **recurse** is set to false.

```
path recurse account fmode dmode
```

This is my **/etc/fix-attrs.d/00-karaf-home-dir**

```
/opt/karaf false karaf 0644 0775
```

When it runs I get the file **fmode** settings applied to the folder.

```
# stat -c '%a' /opt/karaf/
644
```

**Comment by glerchundi** [comment]
Thanks @nigelgbanks for pointing this out. I can confirm that this is a bug in `fix-attrs` script. I'll try to fix ASAP when I get a free slot.

**Comment by glerchundi** [comment]
@nigelgbanks can you take a look to v1.17.1.2, it should fix your issue. If so close this please. Thanks for reporting.

**Comment by nigelgbanks** [comment]
@glerchundi Thanks! **dmode** is applied correctly, but none of the files (immediate children) in the directy have **fmode** applied to them. 

Though that might be by design? If so requiring the extra parameter is confusing. **fmode** probably should be applied to the files in the directory (but not to subdirectories)?

**Comment by snc** [comment]
Is it also by design, that hidden directories and files are ignored?

**Comment by glerchundi** [comment]
@nigelgbanks yeah it's by design. you can put '-' in `fmode` and `fix-attrs` will accept that as argument. Which is semantically more consistent.

@snc same, but maybe it's a design bug: [`s6-ls`](https://github.com/just-containers/s6-overlay/blob/74ec80b67b344be8ddaa801ab61c2b5a9c918624/builder/overlay-rootfs/usr/bin/fix-attrs#L17) doesn't use `-a` argument which includes all files including hidden ones. If you want overlay to behave in a different way please fill a new issue ;)

**Comment by nigelgbanks** [comment]
@glerchundi cool thanks for sorting this so quickly!
