### ISSUE TITLE
Multiple service copies?

### ISSUE THREAD

**Issue by bryanlatten** [just-containers/s6-overlay#138]
analogous to supervisor's `numprocs` setting, is there a way to watch running of multiple instances of a service?

**Comment by glerchundi** [comment]
I don't know if such thing exists in `s6`, @skarnet?

**Comment by bryanlatten** [comment]
as a workaround @glerchundi, I simply made a task[1-x] folder and service definition per copy. worked like a charm.

**Comment by glerchundi** [comment]
cool, thanks for sharing :)

**Comment by skarnet** [comment]
Instanced supervision is something I want to add support for at some point, but it's not a priority since                                                                                                                                                                                  simply having several services by copying service directories is an easy enough way of accomplishing this.
I'd love to have a brainstorming session about instanced supervision, but every time I've asked about it on the mailing-list, I have obtained few reactions and not much substance - so it's in the ice box for now.

**Comment by bryanlatten** [comment]
@skarnet seems like an appropriate priority, its easy enough to work around...and works 100%
