### ISSUE TITLE
can't get a grip on logging

### ISSUE THREAD

**Issue by ehudkaldor** [just-containers/s6-overlay#139]
it took some time, but I finally realize that without setting S6_LOGGING there is no logging happening. not sure if that how it should be, but setting it seems to, at least, kick start logutil-service.

now, i'm not sure how to get logutil-service to use separate files for processes, or, for that matter, use a specific file. 

my /etc/cont-init.d has the file 

> 01.s6-log

 which contains:
```
#!/usr/bin/execlineb -P
exec logutil-service /var/log

```

this creates /logs/postfix/s6-uncaught-logs/current, /logs/postfix/s6-uncaught-logs/lock and /logs/postfix/s6-uncaught-logs/state, and 'current' is the log file. any other path i use in 01.s6-log gets 'path not exist'.

so, how do i tell S6 to log into a specific file in /var/log/ (and not /logs/postfix/s6-uncaught-logs/)? and how do i tell the application to use it? specifically, i am currently building Postfix and Postgresql. how do i direct them to use s6-log, or logutil-xxx?

**Comment by glerchundi** [comment]
instead of putting your `01.s6-log` script inside `cont-init.d` use the standard log mechanism provided by `s6` which allows you tu put you logger per service. So just move that script from that folder to your concrete service folder: `/etc/cont-init.d/01.s6-log` -> `/etc/services.d/yourservicename/log/run`

Please take a look to this: http://skarnet.org/software/s6/servicedir.html
