### ISSUE TITLE
Sending signals to supervised CMD

### ISSUE THREAD

**Issue by thoughtarray** [just-containers/s6-overlay#173]
Is there a way to send a signal (such as a HUP) to the supervised CMD.  In the past I have just made everything services and HUP'd them like so: `s6-svc -h /var/run/s6/services/foo`.  I would like to run the critical service via CMD.

**Comment by thoughtarray** [comment]
I might have not been very clear.  Say that you have a Docker image that has the Foo app and Consul Template in it.  Foo app is running via `/init foo --config /usr/local/etc/foo/foo.cfg` and Consul Template is running as service via a `run` script.

Immagine Consul Template detects a change and rewrites Foo's config script `/usr/local/etc/foo/foo.cfg`.  How can it then send a SIGHUP to Foo?  I could just use `pkill -SIGHUP foo`, but I'd rather use the S6 way via `s6-svc`.

**Comment by thoughtarray** [comment]
@skarnet Any thoughts on this?

**Comment by skarnet** [comment]
The CMD is not supervised, since its death causes the shutdown of the container. That's why you cannot use s6-svc to control it.
 @glerchundi, do we have an environment variable that contains the pid of the CMD ? That would be useful in this case.

**Comment by thoughtarray** [comment]
@skarnet: I see.  Couldn't we supervise it like the others and just have a default finish script that could be overridden?  I feel as though reloading (via signals) critical processes is a pretty common requirement.

**Comment by skarnet** [comment]
That's how I initially envisioned it, yes, but that's not how it was implemented - and I didn't protest because apparently the majority of users wanted their container to stop when the main service was stopped, so it made sense to simply not supervise it. And reloading a config file can usually be done via a SIGHUP or something, without restarting the process, so that's generally not an issue.

 I agree, though, that a way to identify the CMD (i.e. having its pid in an environment variable) would definitely be useful, and I'd like @glerchundi's opinion about it.

However, if you want your critical service to be supervised, I'd really recommend not to make it the CMD - not with the current version of s6-overlay at least. Some time next year we may release a new s6-overlay version that does things differently, but right now we don't have time for a major architectural change; and what you want is currently achievable if you make the critical service a normal, supervised service with a specific finish script that kills the CMD when you want to exit the container.

**Comment by thoughtarray** [comment]
@skarnet: I see.  I had been making all services supervised in the past, but configuring runtime arguments (flags and options) via environment variables seemed a little clunky.  It's no big deal though, I can keep doing things in this manner.

Thanks for clearing that up for me.  I'll use something like `pkill` or configure the critical process via ENV vars for now.

**Comment by skarnet** [comment]
Please leave it open, I'd still like to have @glerchundi and @jprjr's inputs on this :-)

**Comment by thoughtarray** [comment]
@redbaron Oh, nice!  I'm not super familiar with execline scripting or the init scripts, else I'd comment on the PR.

**Comment by jprjr** [comment]
Wrapping CMD into a service wound up breaking things, see https://github.com/just-containers/s6-overlay/issues/221

https://github.com/just-containers/s6-overlay/commit/0f7a212ada723d687fdedbf0672b20e1bad91aae

Closing this out, if somebody can make a PR that implements this in a backwards-compatible, doesn't-break-things way we can re-open and revisit.
