### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by smebberson** [just-containers/s6-overlay#184]
Lots of releases here, which is great, but I can't seem to find any CHANGELOG or anything to keep an eye on what is happening...

Am I just missing it?

**Comment by ffxluca** [comment]
Up

**Comment by NicolasCARPi** [comment]
Hello @jprjr, could you please explain why this issue was closed? Is there a changelog somewhere that I'm missing?

**Comment by jprjr** [comment]
Honestly I'm on the verge of experiencing burnout, I'm not going to write a changelog. If a release warrants a big enough change I'll update the upgrade notes in the README, but short of a complete rewrite or anything, it's mostly bug fixes/maintenance.

If somebody wants to go through the git commits and come up with a changelog and open a PR to update the readme, that would be a huge help.

**Comment by NicolasCARPi** [comment]
@jprjr That's fair. I think the issue is that we're used to have a `CHANGELOG.md` in the root directory or a list of changes in the release text.

I made a PR (#322) to create a maintenance-free changelog, where you can just add the major/breaking changes. I believe it is better than to have it at the bottom of the README. Now it's easier to find ;)

> Honestly I'm on the verge of experiencing burnout

**Your mental health is more important than any piece of software**. Do not hesitate to take a break! I know being an open-source maintainer can be quite demanding, especially for popular projects like this one. Take care and thanks for all the work you already put in this project! :)

**Comment by jprjr** [comment]
Thank. You. So. Much.

I'm honestly tearing up at, y'know, getting a pull request in instead of just being expected to fix every issue myself.

Like yeah it's ultimately not the hardest change ever but it really helps and means a lot to me, so thank you.

**Comment by NicolasCARPi** [comment]
You're welcome. Now go play some videogames ;)
