### ISSUE TITLE
s6-svwait of  /var/run/s6/services/s6-fdholderd bug on alpine

### ISSUE THREAD

**Issue by ekozan** [just-containers/s6-overlay#192]
I try to use `logutil-newfifo /var/run/s6/nginx-access-log-fifo` ( like your nains image ) 
but when i do that `s6-svwait -t 5000 -U /var/run/s6/services/s6-fdholderd` just return `s6-svwait: fatal: timed out`

And i dont figure why :/ 

Any idee ? 

VERSION : v1.18.1.5
OS : Alpine Edge

**Comment by cooperaj** [comment]
Seeing this in an image we're building with debian:jessie (php official image)

It's making figuring out how to log stuff next to impossible. :(

**Comment by jprjr** [comment]
Question: have you removed `/etc/s6/services/s6-fdholderd/down` ?

fdholderd is off by default, I usually have a line in my dockerfiles to remove it

**Comment by trinitronx** [comment]
I'm still seeing this same issue on a base image `amazonlinux:2`, the image AWS maintains based on RHEL / CentOS 7.

The Alpine based image for [just-containers/nginx-loadbalancer][1] appears to work fine.  

However, when I use latest `s6-overlay` on AmazonLinux v2, this same timeout issue happens with the `/etc/cont-init.d/00-initialize-logfifos` script.

The issue was that the following lines were missing, and were added to [`nginx-loadbalancer` image `Dockerfile`][2] to solve this problem:

    # s6-fdholderd active by default
    RUN s6-rmrf /etc/s6/services/s6-fdholderd/down



[1]: https://github.com/just-containers/nginx-loadbalancer
[2]: https://github.com/just-containers/nginx-loadbalancer/blob/master/Dockerfile#L22-L23
