### ISSUE TITLE
supervisor not listening error seen on docker stop

### ISSUE THREAD

**Issue by apratina** [just-containers/s6-overlay#193]
I am getting following error message in docker logs while issuing `docker stop <container id>`
```
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
```

Here is my finish script:
```
#!/usr/bin/execlineb -S1
if { s6-test ${1} -ne 0 }
s6-svscanctl -t /var/run/s6/services
```

We are using `S6_VERSION=v1.18.1.5`. Any suggestions?

**Comment by apratina** [comment]
@glerchundi @skarnet : any suggestions?

**Comment by skarnet** [comment]
`docker stop` sends a SIGTERM to s6-svscan, which is already the equivalent of running `s6-svscanctl -t`. When your finish script runs, s6-svscan has already exec'd into the "stage 3" script, and is simply waiting for all the services to die. The "supervisor not listening" message is truthful - and it's also harmless.

The way to avoid the message is simply not to call `s6-svscanctl -t` in your finish script - but I suppose
you also want to automatically bring down the container when the service exits successfully: in that case, just ignore the message.

**Comment by apratina** [comment]
Is there a way to identify that s6-svscanctl -t has been already called?

**Comment by skarnet** [comment]
Not without a TOCTOU: you can test whether s6-svscan is still listening, but you can't have the guarantee that it will still be the case when you want to use the result of that test. The simplest way to proceed is to actually send a `s6-svscanctl` command - if it succeeds, s6-svscan is running, if it doesn't, it's not :-)
The simplest way of achieving what you want is just to call
`redirfd -w 2 /dev/null s6-svscanctl -t /var/run/s6/services` in your finish script, so that if it fails, the error message will be silenced.

**Comment by apratina** [comment]
Thanks for sharing the info. Closing this issue.
