### ISSUE TITLE
S6_KILL_GRACETIME is mandatory

### ISSUE THREAD

**Issue by YarekTyshchenko** [just-containers/s6-overlay#204]
S6 shouldn't wait the entire grace period, instead it should poll the processes and exit if they are finished, only when the timer reaches `S6_KILL_GRACETIME` it should do the killing

https://github.com/just-containers/s6-overlay/blob/master/builder/overlay-rootfs/etc/s6/init/init-stage3#L54
```
s6-sleep -m -- ${S6_KILL_GRACETIME}
```

**Comment by larscheidt** [comment]
I've been running into this too.  I have a service that occasionally takes a while to stop (MySQL) and I have to set S6_KILL_GRACETIME really high so MySQL isn't SIGKILL'd, but that means the container always take that long to stop.

My attempt at addressing this is below.  I'm unsure if using /bin/sh is okay, but I couldn't find a cleaner way to get the list of service directories.  I added S6_KILL_WAIT_FOR_SERVICES_MAXTIME as a new configuration option so that S6_KILL_GRACETIME could still be used for service finish scripts and any processes outside of s6's supervision tree.

```
@@ -47,10 +47,18 @@
 foreground { s6-echo "[s6-finish] sending all processes the TERM signal." }
 foreground { s6-nuke -th } # foreground is process 1: it survives
+foreground
+{
+
+  backtick -D 10000 -n S6_KILL_WAIT_FOR_SERVICES_MAXTIME { printcontenv S6_KILL_WAIT_FOR_SERVICES_MAXTIME }
+  importas -u S6_KILL_WAIT_FOR_SERVICES_MAXTIME S6_KILL_WAIT_FOR_SERVICES_MAXTIME
+  /bin/sh -c "s6-svwait -d -t ${S6_KILL_WAIT_FOR_SERVICES_MAXTIME} /var/run/s6/services/*"
+}
+
 foreground
 {
 
   backtick -D 3000 -n S6_KILL_GRACETIME { printcontenv S6_KILL_GRACETIME }
   importas -u S6_KILL_GRACETIME S6_KILL_GRACETIME
   s6-sleep -m -- ${S6_KILL_GRACETIME}
 }
```

**Comment by larscheidt** [comment]
I think this has been resolved by the creation of S6_SERVICES_GRACETIME in fe4409d.

**Comment by YarekTyshchenko** [comment]
Nice, this should make a few setups simpler. Ping @webmonkey if you are still using S6 for your images

**Comment by johncronan** [comment]
@YarekTyshchenko @larscheidt

Do you use a CMD, or do you have a service that's the "main" one, with a finish script?

I've done the former, and I have the problem where it always waits for whatever S6_KILL_GRACETIME is set to.

The container log shows that the worker processes that were forked off of that CMD are all receiving SIGTERM:

```
s6-rc: info: service redis successfully stopped
[2022-04-27 00:07:55 +0000] [77] [INFO] Worker exiting (pid: 77)
[2022-04-27 00:07:55 +0000] [79] [INFO] Worker exiting (pid: 79)
[2022-04-27 00:07:55 +0000] [78] [INFO] Worker exiting (pid: 78)
[2022-04-27 00:07:55 +0000] [75] [INFO] Handling signal: term
[2022-04-27 00:07:55 +0000] [75] [WARNING] Worker with pid 79 was terminated due to signal 15
[2022-04-27 00:07:55 +0000] [75] [WARNING] Worker with pid 77 was terminated due to signal 15
[2022-04-27 00:07:55 +0000] [75] [INFO] Shutting down: Master
```

Last line is where it hangs. Maybe it lost track of pid 78? Anyway, my only idea is to try to make this "main" process a service, too. But it was hard enough just to get it all to work in the first place - is that the right approach? Is there something else I might have overlooked?

**Comment by johncronan** [comment]
If anyone finds this, the answer is that it behaves properly as a service with a finish script like this:

```
#!/command/execlineb -S2
s6-svscanctl -t /run/service
```

**Comment by skarnet** [comment]
This is certainly not "behaving properly": if you instruct s6-svscan to kill the supervision tree in the finish script of a service, it will completely hijack the shutdown procedure and may yield very unexpected (and incorrect) results.

Grace time management has been completely reworked in v3 and should be fully operational now; if you are still having issues, they are very probably not related to `S6_KILL_GRACETIME`.

From the log excerpt you have given, it very much looks like your CMD is stuck trying to shut down its master process, but there isn't much information to go on. Can you say how you are starting your container (what is your Dockerfile) and how you are stopping it (what exact command you're running)?

**Comment by johncronan** [comment]
I had other output since then, where it lists every PID. It still outputs the last line and then waits for `S6_KILL_GRACETIME`.

I've committed all this code now: https://github.com/johncronan/formative/tree/dev

If it's broke, I don't know how to fix it.

**Comment by skarnet** [comment]
Ah, now I understand what you mean. Sorry for being slow.
Yes, especially in v3, s6-overlay will always wait for the duration of `S6_KILL_GRACETIME`. Because that timeout does not concern the supervised services, but *all the processes in the container* that have potentially been created by services and are now pending. Including non-supervised processes, which s6 has no way of knowing whether they're alive or not, so it cannot "wait until they're all dead then proceed" as @YarekTyshchenko suggests.

But if you know that you have no ill-behaved services, and that waiting for 3 seconds at container shutdown between SIGTERM and SIGKILL is useless, there's a simple solution for you: set `S6_KILL_GRACETIME` to the minimum possible.

Declare `ENV S6_KILL_GRACETIME=1` in your Dockerfile or your Compose equivalent. Since all your services are already properly shut down when s6-overlay wants to kill everything, the final cleanup will have no impact and your container will be able to exit instantly. (Well, after 1 millisecond. I assume this will not be an issue.)

But please, delete that `finish` script, it is definitely not doing what you want it to be doing.

**Comment by johncronan** [comment]
Yes, from testing it seems they're well behaved, and I don't think it's a possibility to have a process running stuff other than what's already getting signaled. Will do. I can wait one millisecond. 😁

**Comment by YarekTyshchenko** [comment]
@johncronan I've moved on since creating this issue. IIRC it was for a web-server that served some long running requests (it has connected clients stream data from them slowly for hours, by requirement). We used S6 to ensure the webserver (apache iirc) was gracefully shut down via connection draining, while new containers were started.
In that scenario grace time was essentially infinite, which wouldn't do.

IIRC we ended up shipping our own modified init-stage that did the right thing for us, but I no longer have access to it.

Sounds like my solution wouldn't work for your usecase anyway. Does the v3 changes to s6 not work for you?

**Comment by johncronan** [comment]
@skarnet, can I ask one further thing here?

`docker kill --signal=HUP` doesn't do anything for me, with the following `run` script:

```
#!/command/execlineb -P

cd /opt/services/djangoapp/src
with-contenv
s6-setuidgid www-data
gunicorn -c config/gunicorn.conf.py config.wsgi:application
```

But, instead, I can open a container shell, install procps to find my gunicorn pid, and kill -HUP it - that works. Is there an easy fix?

**Comment by skarnet** [comment]
`docker kill` will only ever target pid 1, which is s6-svscan and has no idea that this signal should actually target one of the running services. `docker kill` was basically made for uniprocess containers and is unfortunately unusable in multiprocess containers (except to trigger an immediate shutdown, if the correct signal is used).

I'm afraid there is no easy answer to this. But if your gunicorn process runs as an s6 service, you should never have to look for its pid by hand; instead, you could send it a signal via something like `s6-svc -h /run/service/gunicorn`.

**Comment by johncronan** [comment]
Thanks for that explanation!

Higher up the stack, it's still easy for me to restart as necessary. This only came up because sometimes gotta just hot fix the running server. :)
