### ISSUE TITLE
/usr/bin/with-contenv ignores empty-string vars?

### ISSUE THREAD

**Issue by tmichaud314** [just-containers/s6-overlay#205]
I run a program in an Alpine container and pass some environment variables.  Sometimes, they are assigned an empty string.  The empty string seems to be ignored by `with-contenv`.

After the program's run script executes... given the following `/var/run/s6/container_environment` variable `TASK_CONSTRAINED_EMAIL_ADDRESS`:
```
# ls -la /var/run/s6/container_environment/TASK_CONSTRAINED_EMAIL_DOMAIN
-rw-r--r--    1 root     root             0 Feb 10 00:03 /var/run/s6/container_environment/TASK_CONSTRAINED_EMAIL_DOMAIN
```
I expect `/usr/bin/with-contenv <program>` to include `TASK_CONSTRAINED_EMAIL_DOMAIN` in the environment it sets up for `<program>`.  However, it does not:
```
# /usr/bin/with-contenv env|grep TASK_CONS|wc -w
0
```
It works fine when a variable is assigned to a non-empty string value.

Am I missing something?

**Comment by tmichaud314** [comment]
Reproduction steps using the Docker image [harningt/base-alpine-s6-overlay](https://hub.docker.com/r/harningt/base-alpine-s6-overlay/):
```
$ docker run --rm -it -e NOT_WORKS= -e WORKS=1 harningt/base-alpine-s6-overlay sh
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
/ # ls -la /var/run/s6/container_environment/*WORKS
-rw-r--r--    1 root     root             0 Feb 10 15:10 /var/run/s6/container_environment/NOT_WORKS
-rw-r--r--    1 root     root             1 Feb 10 15:10 /var/run/s6/container_environment/WORKS
/ # with-contenv sh
/ # s6-env | grep WORKS
WORKS=1
```

**Comment by tmichaud314** [comment]
`with-contenv` invokes `s6-envdir`: `s6-envdir [ -I | -i ] [ -n ] [ -f ] [ -c nullis ] dir prog...`

The `s6-envdir` man page says for :
```
* s6-envdir reads files in dir. For every file f in dir, that does not begin with a dot and does not contain the '=' character:
* If f is empty, remove a variable named f from the environment, if any.
```
Ignoring 0-byte-sized files is the expected behavior.  But passing an empty-string-valued env-var is a valid use case.

Perhaps `s6-envdir` could then take an option to preserve 0-byte-sized files?

**Comment by n3v3rf411** [comment]
Been experiencing this issue. I finally gave in to setting `S6_KEEP_ENV` to 1.

**Comment by tripleee** [comment]
I was looking at the source of `with-contenv` just now and wondering if it has a bug. Indeed, to me, it looks like it uses `$@` incorrectly. In both cases, it should use `"$@"` with double quotes around the argument, precisely because not doing so introduces the bug that this report is about (and various other reliability problems with quoted arguments).

See, for example, https://mywiki.wooledge.org/Quotes#Examples -- I quote (sic):

> Proper iteration over the positional parameters using a quoted `"$@"`. Never use an unquoted `$@` or `$*`.

**Comment by jprjr** [comment]
Release v2.0.0.0 now supports empty files for creating empty variables

**Comment by johncronan** [comment]
> I was looking at the source of `with-contenv` just now and wondering if it has a bug. Indeed, to me, it looks like it uses `$@` incorrectly. In both cases, it should use `"$@"` with double quotes around the argument, precisely because not doing so introduces the bug that this report is about (and various other reliability problems with quoted arguments).

Aha! Finally the weird behavior that I'm seeing makes sense. I've been trying to use with-contenv with the shell. There's a bug. The first command in the script doesn't execute correctly, when a later command in that same script uses a double-dash argument, `--something`. Reading the above, I remembered that the shell has some kind of special handling for the double-dash. @jprjr, should I open a new issue?

Here's a minimal recreation:
```
#!/command/with-contenv sh
touch foo
ls --color
```

> formative-djangoapp-1  | touch: unrecognized option '--color'
> formative-djangoapp-1  | Try 'touch --help' for more information.
> formative-djangoapp-1  | s6-rc: warning: unable to start service setup2: command exited 1

**Comment by jprjr** [comment]
I don't think @triplee's assessment was ever correct - because `with-contenv` is not written in bash/posix shell, but in execline, which has very different quoting rules. Long-story short, `$@` (without quotes) is perfectly fine in execline and shouldn't cause issues. In fact, quoting it would do the opposite of what you want - in execline, anything in quotes always expands to a single argument. The issue with empty environment variables not persisting was due to how `s6-envdir` dealt with empty files.

On my Docker setup, the example script works fine. I usually create scripts with `#!/command/with-contenv /bin/sh` (the full path to the shell I intend to use). Is something causing `sh` to not be in the search path? What happens with `/bin/sh`

This looks more like the script is somehow not being handed off to `sh`, since execline scripts treat newline the same way bash treats a space (so in this example, it's constructing a command like `touch foo ls --color` - all one command).

**Comment by johncronan** [comment]
Thanks!

I tried replacing 'sh' with '/bin/sh' and got the same error.

Here's my Dockerfile:

```
FROM debian:bookworm-slim

RUN mkdir -p /opt/services/djangoapp/src /opt/services/djangoapp/static
WORKDIR /opt/services/djangoapp/src

COPY pyproject.toml poetry.lock /opt/services/djangoapp/src/

# dependencies
RUN apt-get update \
    && apt-get install -y build-essential libpq-dev libqpdf-dev pip xz-utils \
                          python3-dev python3-importlib-metadata wget redis \
    && apt-get install -y --no-install-recommends ffmpeg \
    && pip install wheel poetry && poetry config virtualenvs.create false \
    && poetry install --no-dev --no-root -E reviewpanel \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get purge -y --auto-remove build-essential
# virtualenvs.create option because we don't need an extra virtualenv here

COPY . /opt/services/djangoapp/src
# install the root package too
RUN poetry install --no-dev

COPY resources/s6-rc.d /etc/s6-overlay/s6-rc.d
ARG S6_VERSION=3.1.0.1
ARG S6_URL=https://github.com/just-containers/s6-overlay/releases/download
RUN arch="$(dpkg --print-architecture)"; \
    case "$arch" in arm64) s6arch='aarch64' ;; amd64) s6arch='amd64' ;; esac; \
    wget -O s6.tar.xz ${S6_URL}/v${S6_VERSION}/s6-overlay-noarch.tar.xz; \
    wget -O s6arch.tar.xz ${S6_URL}/v${S6_VERSION}/s6-overlay-$s6arch.tar.xz; \
    tar -C / -Jxpf s6.tar.xz; \
    tar -C / -Jxpf s6arch.tar.xz; \
    rm s6.tar.xz s6arch.tar.xz

EXPOSE 8000

ENTRYPOINT ["/init"]
```

This is such a weird problem. I really appreciate your help.

**Comment by johncronan** [comment]
Ah, here we go. Try changing the rootfs to this

```
rootfs/
 └── etc
     └── s6-overlay
         └── s6-rc.d
             └── user
                 └── contents.d
                     └── demo
                 └── demo
                     └── type
                     └── up
 ```

With contents of type

```
oneshot
```

and `up` the same as the contents of demo, before.

I got the error, unrecognized option: color.

**Comment by skarnet** [comment]
`up` doesn't read the shebang, it's _always_ interpreted by execline. Don't write shell scripts in `up`.
The explanation is in the [README.md](https://github.com/just-containers/s6-overlay/blob/master/README.md) file: look for `weird syntax` and click on the link to expand the text.

**Comment by johncronan** [comment]
Damn, ok. I'm pretty sure that was copied from instructions I found somewhere. I guess they were wrong. I thought I had pored over every inch of your documentation, but I didn't notice that expandable text. Thank you.

Would you mind telling me how to test that an environment variable is non-empty and if so, run a command?

This is the spot I'm trying to do it:
https://github.com/johncronan/formative/blob/453c3d38ac1d08f44572ae182d95e72368a0b74a/resources/s6-rc.d/setup3/up#L4

**Comment by skarnet** [comment]
So again, you shouldn't need to worry about it - you could just write your script in the language of your choice (typically shell) in a different file and just call that file in your `up` script. But if you want to keep your current `up` script:
- execline doesn't automatically import environment variables, you have to use the [importas](https://skarnet.org/software/execline/importas.html) program for this;
- execline makes a difference between an undefined variable and a non-empty variable, so you'll need to decide what to do in which case
- if the difference isn't important to you, here is how to do what you want:
```
cd /opt/services/djangoapp/src
if -t
{
  importas -D "" AUTO_MIGRATE AUTO_MIGRATE
  test -n $AUTO_MIGRATE
}
with-contenv
python3 manage.py migrate --noinput
```

Note the `-t` option to `if`, because if AUTO_MIGRATE is undefined or empty, I suspect you want the script to do nothing but still succeed - and without `-t`, `if` would return failure if the test is false, so the transition would be considered failed.

Also note the absence of a shebang. Writing a shebang makes the reader believe that the interpreter can be changed, but here a shebang would just be ignored as a comment and only be misleading.

**Comment by johncronan** [comment]
Oh okay, that makes a lot of sense now. Thank you!

I had discovered `importas`, but the latter aspect eluded me, and I think that was why one side or the other of the branch was messed up, no matter what I tried.

I'll take the shebangs out, too, so I don't forget what's up.

**Comment by johncronan** [comment]
I stuck it out with the execline, since I've come this far. I had to move `with-contenv` up to the top because `importas` needs it too.

**Comment by skarnet** [comment]
Ah, yes, of course.
