### ISSUE TITLE
S6 causes hang out for Docker container in travis

### ISSUE THREAD

**Issue by izonder** [just-containers/s6-overlay#221]
Dockerfile: https://github.com/izonder/anny/blob/master/Dockerfile
S6-overlay ver: 1.21.x.x
Behavior: it causes hang out and test failure in travis

Travis log output:
```
$ docker run -it --rm izonder/anny node -v
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

Running the command from Ubuntu works properly as expected. The problem has appeared since version 1.21.0.0, version 1.20.0.0 doesn't cause such problems (that's why I had to roll back to v.1.20.0.0).

**Comment by jprjr** [comment]
It looks like changes from #149 introduced some weirdness when running on travis, possibly due to how travis uses some type of virtual TTY for logging. It seemed like running a container with no services was fine, but starting nginx introduced errors, possibly with signal timing? I'm not 100% sure, to be honest.

I've gone ahead and reverted it, I'm not entirely if auto-wrapping a` CMD` into a service had great benefits compared to the complications it introduced. `s6-overlay` now uses the old behavior of running in the foreground. Version `1.21.2.1` should work properly
