### ISSUE TITLE
prefer wget/curl over add to make steps cacheable

### ISSUE THREAD

**Issue by grosser** [just-containers/s6-overlay#232]
running with 

```
ADD https://github.com/just-containers/s6-overlay/releases/download/v1.21.4.0/s6-overlay-amd64.tar.gz /tmp/
```

always does a download even if I just built the image ... it also produces 2 layers ... prefer using wget to make the layer cacheable ?

```
RUN \
  wget -O /tmp/s6.tar.gz https://github.com/just-containers/s6-overlay/releases/download/v1.21.4.0/s6-overlay-amd64.tar.gz && \
  tar xzf /tmp/s6.tar.gz -C /
```

**Comment by jprjr** [comment]
Yeah, that's a frustration with Docker - it always has to download remote files when you use `ADD`

I figure that people can figure out how to best grab files for their Docker images. That chunk of the README is just meant to be a quick "Hey, here's how to quickly try this out." There's no great "one size fits all" - like how CentOS users have to extract in two steps, otherwise they destroy their `/bin` directory.

**Comment by grosser** [comment]
... maybe add a "prefer curl/wget to avoid downloading on each build" :)
... close if you want, I got my own version now ...
