### ISSUE TITLE
install instructions no longer work

### ISSUE THREAD

**Issue by shadycuz** [just-containers/s6-overlay#239]
Running...
```
######### Setup S6-Overlay
ADD https://github.com/just-containers/s6-overlay/releases/download/v1.21.2.2/s6-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C /

######### Setup Deluge
RUN echo hey
```

gives me this...
```
Step 2/16 : ADD https://github.com/just-containers/s6-overlay/releases/download/v1.21.2.2/s6-overlay-amd64.tar.gz /tmp/
Downloading [==================================================>] 1.712 MB/1.712 MB
 ---> Using cache
 ---> 14cb66b42d08
Step 3/16 : RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C /
 ---> Using cache
 ---> c88ae8541612
Step 4/16 : RUN echo hey
 ---> Running in 963d04f768a7
OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": unknown
```

running...
```
######### Setup S6-Overlay
ADD https://github.com/just-containers/s6-overlay/releases/download/v1.21.2.2/s6-overlay-amd64.tar.gz /tmp/

######### Setup Deluge
RUN echo hey
```
gives me this...
```
Step 2/15 : ADD https://github.com/just-containers/s6-overlay/releases/download/v1.21.2.2/s6-overlay-amd64.tar.gz /tmp/
Downloading [==================================================>] 1.712 MB/1.712 MB
 ---> Using cache
 ---> 14cb66b42d08
Step 3/15 : RUN echo hey
 ---> Running in 16b7e4d0e746
hey
```

It used to work? not sure what changed. Same results even if I turn off build cache.

**Comment by jprjr** [comment]
What docker image are you using in your FROM line?

**Comment by shadycuz** [comment]
It's nested like three levels deep, but the first image is debian

**Comment by jprjr** [comment]
What version of debian, specifically?

I don't *think* debian replaced /bin with a symlink to /usr/bin, but I'd have to know the specific version to look that up.

**Comment by shadycuz** [comment]
I was planning on working on it all day tomorrow, but let me try and get
that info here in like 20 mins

**Comment by jprjr** [comment]
Yeah, looks like they've done that. I have a workaround in this comment: https://github.com/just-containers/s6-overlay/issues/239#issuecomment-417938780

**Comment by dreamcat4** [comment]
Hey there @jprjr. Have also been hit by this issue recently. It is something that started happening since ubuntu 19.04.

It is just there may be a simpler workaround that would then be be better for everybody to adopt. 

This error is something which is expecially more difficult for newcomers to but 2 + 2 together and find that other solution amongst the documentation. Especially if they are pressed for time, etc. And also because the error message being presented to the user: it says nothing whatsoever about the cause being due to a symlink of `/usr/bin` getting overwritten.

So here is an alternative way. Which is also noob friendly, and just a much simpler solution:

If we replace all (the readme instructions), all the instances of:

```sh
tar xzf /tmp/s6-overlay-amd64.tar.gz -C /
```

with:

```sh
tar hxzf /tmp/s6-overlay-amd64.tar.gz -C /
```

Then passing that extra little `-h` flag into `tar` will ensure that any existing symlinks being encountered by `tar` will not be overwritten on the destination. They are simply followed instead as if they were real folders (as previously). I have tried this yesterday and it seems to work fine in my images. And it should not have no effect whatsoever on those users who are not being affected by this issue. Assuming that we are not relying on obliterating existing symlinks somewhere else in `s6` for any obscure reason.

The main advantage is that you no longer need an exclusive exception that is more complex. Nobody needs to encounter this issue anymore (breaking their builds with a strange error message which is not very helpful). And since this change (being put forwards by Freedesktop.org), I suspect it may be becoming a lot more widespread in the future. As more other distributions begin to adopt it. Not just ubuntu. Then it should really become the default instructions in the quiststart and other sections. If it comes a time when (overall) more distributions (well, more total installations) are using this scheme than are not.

I am under the impression that this solution should work just as well as your other existing workaround. And without any detriment / or breaking anything else. However there are quite a few more complex parts of `s6` which I simply don't have any reason for using. So therefore perhaps you can come back to this matter once again @jprjr ? And give it a 2nd look? Many thanks.

Here is a container startup log, from a recent image that was built with s6 being installed in this simpler way, simply by adding `tar h` flag:

https://gist.github.com/dreamcat4/b8aefa20dfbab12374a51d30301aa836

https://github.com/dreamcat4/docker-images/blob/master/dockerdns/Dockerfile#L8

**Comment by jprjr** [comment]
I had no idea about that 'h' flag! Your dockerfile is based on Alpine, can you check on a few other distros? I'm pretty sure Alpine is using BusyBox for its Tar implementation.

If so, let's update the readme with that new invocation as a default. Maybe with some extra text like "if you receive an error about the 'h' flag not being supported, do this" - with the old, two-call workaround steps.

I do think at this point, we need to assume /bin is a symlink

On August 20, 2019 3:52:55 AM EDT, Dreamcat4 <notifications@github.com> wrote:
>Hey there @jprjr. Have also been hit by this issue recently. It is
>something that started happening since ubuntu 19.04.
>
>It is just there may be a simpler workaround that would then be be
>better for everybody to adopt. 
>
>This error is something which is expecially more difficult for
>newcomers to but 2 + 2 together and find that other solution amongst
>the documentation. Especially if they are pressed for time, etc. And
>also because the error message being presented to the user: it says
>nothing whatsoever about the cause being due to a symlink of `/usr/bin`
>getting overwritten.
>
>So here is an alternative way. Which is also noob friendly, and just a
>much simpler solution:
>
>If we replace all (the readme instructions), all the instances of:
>
>```sh
>tar xzf /tmp/s6-overlay-amd64.tar.gz -C /
>```
>
>with:
>
>```sh
>tar hxzf /tmp/s6-overlay-amd64.tar.gz -C /
>```
>
>Then passing that extra little `-h` flag into `tar` will ensure that
>any existing symlinks being encountered by `tar` will not be
>overwritten on the destination. They are simply followed instead as if
>they were real folders (as previously). I have tried this yesterday and
>it seems to work fine in my images. And it should not have no effect
>whatsoever on those users who are not being affected by this issue.
>Assuming that we are not relying on obliterating existing symlinks
>somewhere else in `s6` for any obscure reason.
>
>The main advantage is that you no longer need an exclusive exception
>that is more complex. Nobody needs to encounter this issue anymore
>(breaking their builds with a strange error message which is not very
>helpful). And since this change (being put forwards by
>Freedesktop.org), I suspect it may be becoming a lot more widespread in
>the future. As more other distributions begin to adopt it. Not just
>ubuntu. Then it should really become the default instructions in the
>quiststart and other sections. If it comes a time when (overall) more
>distributions (well, more total installations) are using this scheme
>than are not.
>
>I am under the impression that this solution should work just as well
>as your other existing workaround. And without any detriment / or
>breaking anything else. However there are quite a few more complex
>parts of `s6` which I simply don't have any reason for using. So
>therefore perhaps you can come back to this matter once again @jprjr ?
>And give it a 2nd look? Many thanks.
>
>Here is a container startup log, from a recent image that was built
>with s6 being installed in this simpler way, simply by adding `tar h`
>flag:
>
>https://gist.github.com/dreamcat4/b8aefa20dfbab12374a51d30301aa836
>
>https://github.com/dreamcat4/docker-images/blob/master/dockerdns/Dockerfile#L8
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/just-containers/s6-overlay/issues/239#issuecomment-522899093

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dreamcat4** [comment]
Yes John. ATM I am mostly on `ubuntu:18.04` (for most of my other images). However also planning to upgrade these all to `ubuntu:19.04` fairly soon. Which is a distro / version that now affected by this change.

So what I shall be doing, is to take some more container startup logs of certain containers / images based on `18.04` instead. (rather than apline or whatever). And have nothing else changed, only altering the base image to `19.04`. So that we can make a direct comparison in the startup logs. To see if there is anything in there different in the output being printed by s6.

But before I go ahead and do that, please let me know if I need to turn on any extra logging or other features in s6 to test. Here is a link to one of my images where I plan to test this: so you can see how I am currently using `s6` in ubuntu...

https://github.com/dreamcat4/docker-images/blob/master/forked-daapd/Dockerfile

In case there is anything else you need me to add to it for better logging etc. then please let me know. Kind Regards.

**Comment by dreamcat4** [comment]
In terms of the `-h` flag possibly not being supported in some environments:

I would expect that usually most / all of the really space constrained smaller distributions are based on some version busybox. If not that then what else?

So I checked the official busybox docker image, and the oldest version of it that is available up on Dockerhub is 4 years old. Version `busybox:1.23`. Well that earliest version already included the `h` flag to follow symlinks.

Then I checked the busybox changelog. And as far as I can tell, it's always supported this option for as far back as that goes.

So then I also checked the changelog for GNU Tar program too. And that also does not mention ever introducing the `h` flag. The implication being the same again - that it's always been there since the beginning.

Not sure what other places to check. Other than some really old `tar` version. Like on some really old unixes. Before the days of Linux and GNU tar. But I would not be able to check up on those and they are not going to be used very much (anymore) at this point.

So my overall conclusion is that: It would seem that the `h` flag is pretty much universally supported by tar and busybox.

**Comment by dreamcat4** [comment]
OK @jprjr! Time for an update.

Looked into this matter a lot more deeply since we last discussed. And here are my conclusion(s):

Re-Stating the problem:

* The `s6-overlay` (this git repo) is inherently not compatible with BOTH the new freedesktop.org way of doing things. And also maintain compatibility with the old layout at the same time too.

* This is a problem! And it isn't going to ever go away all by itself. Because we have a world with a mixture of distributions. Some using the old way and other using the new one. And not having this changes being obvious to the end user when the distro silently changes it's next version to the new layout. Which is those reasons I had explained previously.

* The reason for this current incompatibility within s6-overlay is because the symlink of `/usr/bin/execlineb --> /bin/execlineb` is a dirty hack. And lets this project continue to be self-inconsistent in the way it references multiple different locations for the `execlineb` program. With executable having to be in both of those places. Either expecting `execlineb` to be in `/bin/` sometimes. Or in `/usr/bin/` at other times. Not good!

* I have now determined (as far as I can tell): That this does not seem to be an upstream issue. This seems to be an issue which is specific to this project (in this git repo, not in the other builders). Unless there is some issue for setting the default output location of `execlineb` program, when it is being built? I'm not sure.


The suggested solution:

* First of all, make 2 identical hard copies of the `execlineb` program in both places. This is very much an interim step. This gets rid of a new problem that will otherwise occur with circular symlink when tar archive is unpacked. So we much remove that dirty hack. And that is the initial step.

* Then, we also need to be changing the few existing references of `/bin/execlineb` to be `/usr/bin/execlineb` instead. Which is not very difficult to do. It only occurs in the 1st lines of `/init` and `/init-stage1` etc...

* So then all of the references within this project will finally be self consistent. With a new location of `/usr/bin/execlineb` instead. And not have anything expect it to be in `/bin/` anymore.

The main reason why `execlineb` has to move to `/usr/bin` is because:

All the existing and long standing examples in the `README.md` file here have always said to use this shebang line: `#!/usr/bin/execlineb`. So doing anything else would break the exiting images of any users of s6-overlay. Anybody who had been using those examples. (which I would expect is: pretty much everybody!). So there is not much choices anymore about that now, at this point. It really has to be done that way.

We could then being to use the `tar h` flag safely, and universally. But that is only something for future versions of s6-overlay going forwards. After making those initial changes. Once those above things have been fixed.

* Then at some later (future) versions of `s6-overlay` we can eventually remove the duplicate copy of `/bin/execlineb`. Which was the old location of it. And nobody should be affected by the new `tar h` instruction breaking the previous versions of `s6-overlay`.

Otherwise it is never going to be possible to have a simple and universal 'one liner' instruction that is the same for all of the users. Ahem. It's all pretty silly I know. Nobody really asked for this kinds of breakages.

Well I can explain a bit further if you like. But this problem is an inherent one. It isn't going away by itself. We should make all the references within this project point consistently to the same location. There is simply not any other way to do it properly.

Just wondering now how the output location of `execlineb` program is chosen in the builders. Because that is not something which I understand.

If we were to do that a first phase (for some a while). Then eventually phase that old location out once everybody had upgraded their s6 versions to be 'at least' the new version where we had already removed all those inconsistent references to `/bin/execlineb` program. And also update to new univeral `tar h` instruction. I am guessing that is probably the best way forwards here. Since we cannot make these distros / freedesktop.org cancel this changes. It seems they have already been doing this for quite some time now.

And that is my best suggestion! Sorry, had initiall hoped it would be much simpler than all that ^^. However clearly we don't want to break anybody else's existing stuff. So going for a phased approach would very much help to avoid that.

Again - sorry that I'm not sure how to change that in the other builder images. They are a bit complicated for me to probe into / look what they are doing from over here.

**Comment by dreamcat4** [comment]
Until then,

1. Works for old distros but not for new convention, in newer distros:

```sh
RUN tar zxhf /tmp/s6-overlay-amd64.tar.gz -C / && $_clean
```

2. Works for new but not for old:

```sh
RUN tar zxhf /tmp/s6-overlay-amd64.tar.gz -C / --exclude=usr/bin/execlineb && $_clean
```

3. Works for both, but is kludgy and hackish:

```sh
RUN tar zxhf /tmp/s6-overlay-amd64.tar.gz -C / --exclude=usr/bin/execlineb \
 && tar zxhf /tmp/s6-overlay-amd64.tar.gz -C /usr ./bin/execlineb && $_clean
```

So if making the suggested changes, then the **method 1.** solution would work for all of the distros.
