### ISSUE TITLE
Expose CMD to init scripts

### ISSUE THREAD

**Issue by chrismccracken** [just-containers/s6-overlay#242]
There are certain situations where the behavior of the init scripts needs to vary depending on the  CMD that is passed to the container. It would be very helpful to have the Docker CMD that was passed in exposed to the init tasks as an environment variable.

**Comment by jprjr** [comment]
This one is tricky since CMD isn't (necessarily) a simple string, it's usually an array.

I can store it in some encoded format (like a series of netstrings, json, quoted strings), but I'm not sure if there's a good way to get it back into the shell without clobbering over $@ (which is the only array posix sh supports).

I'd suggest restructuring the app so services are independent of the CMD, especially since CMD can be literally anything.
