### ISSUE TITLE
How to pass variable from cont-init.d to service.d ?

### ISSUE THREAD

**Issue by lukasmrtvy** [just-containers/s6-overlay#243]
How to pass variable from cont-init.d to service.d ?

For example cont-init.d/50-config:
```
#!/usr/bin/with-contenv bash
export OPTION="${CUSTOM_OPTION:-foo}"
```

services.d/myservice/run:
```
#!/usr/bin/with-contenv bash
exec s6-setuidgid user myservice ${OPTION}
```

Expected results:
Run `exec s6-setuidgid user myservice foo, if CUSTOM_OPTION is not overriden from docker run -e CUSTOM_OPTION= `

Thanks

EDIT:
seems that `printf "YOURVALUE" > /var/run/s6/container_environment/YOURENV` will do the trick

**Comment by jprjr** [comment]
That's exactly what I would do.

Another option is to make an envdir for that specific service and import it with s6-envdir, that way you don't pollute the global environment.

But since most containers are (or should be) small, polluting the global environment isn't a big deal.

**Comment by AmazingDonut** [comment]
I believe if `S6_KEEP_ENV` is set, then `/var/run/s6/container_environment/` is ignored? Are there are any other recommended workarounds for passing variables between scripts?

**Comment by jprjr** [comment]
Yeah - you could make a custom envdir just for that service and call `s6-envdir` or `justc-envdir` in your run script.

You won't be able to call it from your `#!` line like you `with-contenv` - if I recall correctly, the Linux kernel only recognizes the first space.

So this works -

```bash
#!/usr/bin/with-contenv bash
```

But this doesn't because of multiple spaces

```bash
#!/usr/bin/justc-envdir /path/to/some/envdir bash
````

So you've got some options:

## First make an envdir

All these examples assume you've made a custom envdir. From a script in cont-init.d you could do something like:

```bash
#!/bin/sh

mkdir -p /var/run/my_env
printf "VALUE" > /var/run/my_env/KEY
```

## Option 1: Use execline

In execline, everything is "chained" together and exec'd by default, so you can write:

```bash
#!/usr/bin/execlineb
justc-envdir /var/run/my_env whatever-your-service-is
```

## Option 2: exec-chaining

This won't work if your `run` script relies on these environment variables, they won't get populated into your `run` script, just into the program you're supervising

```bash
#!/bin/sh 
exec justc-envdir /var/run/my_env \
whatever-your-service-is
```

## Option 3: Wrap the call to justc-envdir in a script

You can basically write your own `with-contenv` this way:

```
#!/bin/sh 
exec justc-envdir /var/run/my_env "$@"
```

Save that somewhere, then in your `run` script

```
#!/usr/bin/that-script-i-just-wrote bash
echo "Look at this: ${KEY}" # environment variables from the envdir are available to your script now
exec whatever-your-service-is
```
