### ISSUE TITLE
Rationale of s6-sync? way to disable it?

### ISSUE THREAD

**Issue by mauri** [just-containers/s6-overlay#244]
Hello, what's the rationale of running the s6-sync utility in a container when it's shutting down? 

Looks like it only runs a sync() syscall, which tries to sync ALL block devices in a host. I've seen situations when having an issue in a block device would affect all the containers in a host, even if they were not using any block device, making it impossible to shut them down sync s6-sync hangs. Is there a way to disable it?

**Comment by jprjr** [comment]
I think you're right - since `sync` can "break out" of the container, and containers (usually) don't have their own block devices, it's not a good idea to call "s6-sync" unless you specifically know you need it (ie, you attach a device using `--device`).

I've made it optional, I'll be bumping the major version number to indicate this is a breaking change (in case anybody was relying on the call to `s6-sync`).
