### ISSUE TITLE
can we make cont-init.d scripts run _only_ at container first start?

### ISSUE THREAD

**Issue by ehudkaldor** [just-containers/s6-overlay#253]
I have the following situation:
I am running an container simulating a real application. when the application starts, it generates a random token which is then used by the application's clients.
part of the tests are restarting the container, but when I run `docker restart` the cont-init.d scripts run again, which changes the token and breaks everything.

so, the question is: is there a way to have the init scripts run only the first time the container starts, and not later?

I know I can solve that with some flag after the first pass, but I wonder if there is a built-in, more elegant way of doing so.

**Comment by jprjr** [comment]
Well, for things like tokens and other pieces of data that need to stick around I'd recommend using a volume or grabbing the token from an environment variable. If using a volume, your script should check if the token already exists before regenerating it.

I run all my containers with the `--rm` flag set and never use `docker restart`. It helps me ensure that I retain all needed data between runs, since I can't rely on storing any data in the actual container.
