### ISSUE TITLE
How to skip startup of a specific service?

### ISSUE THREAD

**Issue by georgeboot** [just-containers/s6-overlay#267]
We're using s6 to master our image that contains both nginx, php and a few other things. By default, all the services defined in `/etc/services.d` need to starup.

However, we would like the same image to run in multiple ways. By default it runs as a full webserver, but sometimes we only want to run the queue worker part, and thus not startup nginx and php.

It would be ideal if this could be achieved using env variables. I've already tried reading an env variable in the bash script, but it seems that s6 is expecting a new pid to be created when it runs the server startup script.

Any suggestions on what might work?

**Comment by SloCompTech** [comment]
Hi,
if you use bash in run file, you can do:
``` bash
#/bin/bash

#...

if [ -n "$SKIP_SERVICE" ]; then
  exit 0
fi

#....
```

**Comment by bryanlatten** [comment]
@georgeboot we do the inverse, symlinking folders into services.d when available to run:
https://github.com/behance/docker-nginx/blob/master/container/root/run.d/99-nginx.sh#L13

**Comment by jprjr** [comment]
There's a few options, best is to symlink them in at run-time in a cont-init.d script.

Another option is to create all your service directories with `down` files and remove them at runtime, though this requires a writable root filesystem. Same with @bryanlatten's answer.

Copying them into `/var/run/s6/services` is safer since we require `/var` to be writable. `/etc/` may be read-only.

Keep your conditional service directories out of `/etc/services.d` (maybe something like `/etc/services-available`), then put a script under `cont-init.d` like:

```bash
#!/bin/sh

if [ $WHATEVER_ENABLES_YOUR_SERVICE -eq 1 ] ; then
  s6-hiercopy /etc/services-available/your-service /var/run/s6/services/your-service
fi

s6-svscanctl -a /var/run/s6/services
```
