### ISSUE TITLE
Bring down whole container if service cannot be restarted

### ISSUE THREAD

**Issue by FedericoPonzi** [just-containers/s6-overlay#277]
If I have a mysql container that for some *bad* reason crashes, is it possible to specify something like " retry to restart this container 5 times with a incremental backoff time, and if it doesn't stay alive bring down the whole container?"

**Comment by jprjr** [comment]
I think so - there's the [s6-svdt](https://skarnet.org/software/s6/s6-svdt.html) program, which returns the death tally of a service. One death per line.

You'd want to write a `finish` script that calls it and parses it (or at least counts the lines). When you've hit 5 deaths, call `s6-svscanctl -t /var/run/s6/services` and exit with code 125.

Otherwise, call sleep for some period of time, then exit 0. Incremental backoff could probably be accomplished by using the number of failures as a multiplier.
