### ISSUE TITLE
Drop privileges for CMD

### ISSUE THREAD

**Issue by felipecassiors** [just-containers/s6-overlay#286]
How this can be accomplished?

Currently, I'm using:

```dockerfile
ENTRYPOINT [ "/init", "gosu", "jenkins" ]
CMD [ "bash" ]
```

**Comment by jprjr** [comment]
```Dockerfile
ENTRYPOINT ["/init", "s6-setuidgid", "jenkins"]
CMD ["bash"]
```

**Comment by felipecassiors** [comment]
When I do this, I receive the following error

```bash
bash: /root/.bashrc: Permission denied
```

**Comment by jprjr** [comment]
There's likely some environment variables you'll want to reset, like `HOME` is probably still pointed at `/root`.

Something like:

```Dockerfile
ENTRYPOINT ["/init", "export", "HOME", "/home/jenkins", "s6-setuidgid", "jenkins"]
CMD ["bash"]
```

(replace "/home/jenkins" with whatever the actual home directory is)

You could also call execline and pass a whole string as a script:

```Dockerfile
ENTRYPOINT ["/init", "/bin/execlineb", "-s0", "-c", "export HOME /home/jenkins s6-setuidgid nobody $@"]
CMD ["bash"]
```

I find that a little easier to read and deal with

**Comment by DarkGhostHunter** [comment]
Sorry to reopen this dead body, but can be this done at runtime?

For example, calling a script that retrieves the username and mapping, and use that to run the container, otherwise continue as `root` or the default set in `--user`.

I'm asking this because some software have sketchy Docker support and running a container as root breaks all permissions, unless mapped manually at build time and it's a PITA.

**Comment by skarnet** [comment]
It's been a while and s6-overlay has changed a lot, version 3 operates in a fairly different way. (You've switched to v3, haven't you? We don't provide support for v2 anymore.)

Can you please open a different issue instead and explain exactly what you want to do? It's likely that v3 already has your use case baked in.
