### ISSUE TITLE
Ubuntu 19.10 symlink issue.

### ISSUE THREAD

**Issue by Grimeton** [just-containers/s6-overlay#288]
Hello,

I'm trying to build a container image with Ubuntu 19.10 and run into a problem with "/bin" being a symlink to "/usr/bin" inside the container. When I extract the overlay, tar removes the symlink, creates "/bin" and fills it with the tarball's contents. Afterwards the shells are inaccessible, as they reside only in "/usr/bin" now. 

I'm basically using the example from the main github page. Except I change the image version to "ubuntu:rolling". 

I figured before anyone else runs into this I'll let you know that you have to add the "h" option on EXTRACT of the archive like so:

tar fhvxz s6-overlay-amd64.tar.gz -C /

Et voila..

KR,

G.

**Comment by dreamcat4** [comment]
Hey @Grimeton - this matter was already raised to the maintainer months ago and he never replied / never took action / never fixed it. Sorry to hear that after all this time you also had to suffer this matter. Totally avoidable.

**Comment by dreamcat4** [comment]
This issue is the same as https://github.com/just-containers/s6-overlay/issues/239

**Comment by Grimeton** [comment]
Is this still maintained?

**Comment by jprjr** [comment]
I'll be honest, I've had a few life changes and it's drastically 
reduced the amount of free time I have. My previous job used 
s6-overlay so I was able to maintain it at work, now I'm limited to 
maintaining in my free time.

I'll happily accept pull requests to fix issues.

**Comment by Grimeton** [comment]
> I'll be honest, I've had a few life changes and it's drastically
reduced the amount of free time I have.

I know the problem. As @dreamcat4 seems to have all the solutions to this particular problem, I wonder if he could create a pull request?

**Comment by dreamcat4** [comment]
For a PR ? Lets see then:

This was the suggested documentation only change that was suggested for everybody. As a new single and universal instruction that can work for all:

```sh
RUN tar hzxf /tmp/s6-overlay-amd64.tar.gz -C / --exclude=usr/bin/execlineb \
 && tar hzxf /tmp/s6-overlay-amd64.tar.gz -C /usr ./bin/execlineb && $_clean
```

However that is not very elegant (whatsoever). And whilst simple to change seems like the wrong thing to do.

===

To instead solve it properly? And not require such a poor looking changes for the official usage instructions?

> The suggested solution:
> 
>    First of all, make 2 identical hard copies of the execlineb program in both places. This is very much an interim step. This gets rid of a new problem that will otherwise occur with circular symlink when tar archive is unpacked. So we much remove that dirty hack. And that is the initial step.
> 
>    Then, we also need to be changing the few existing references of /bin/execlineb to be /usr/bin/execlineb instead. Which is not very difficult to do. It only occurs in the 1st lines of /init and /init-stage1 etc...
> 
>    So then all of the references within this project will finally be self consistent. With a new location of /usr/bin/execlineb instead. And not have anything expect it to be in /bin/ anymore.

Then: 

`RUN tar hzxf /tmp/s6-overlay-amd64.tar.gz -C / && $_clean`

Will work after making these suggested changes, and will work for all of the distros without any issue. And is the most reasonable line to tell people to put inside their `Dockerfiles` going forwards.

Why no PR exists?

> Just wondering now how the output location of execlineb program is chosen in the builders. Because that is not something which I understand.

> Again - sorry that I'm not sure how to change that in the other builder images. They are a bit complicated for me to probe into / look what they are doing from over here.

That is the 1 place where I was lacking the necessary knowledge to perform necessary changes. To make the PR. And I have not looked at the s6-overlay repos since. therefore still don't know the answer (myself!) as I am not the maintainer of this project, or persons who setup those build system - @glerchundi ? How does it work? To generate a 2nd identical (real) copy of `execlineb` program in `/usr/bin` location. In addition to `/bin` as currently. Instead of the symlink. Does not sound too terribly hard, does it? Thank you.

**Comment by Grimeton** [comment]
IMHO this should all be put into /usr/local/ and then used from there. 

https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.pdf might help us here. 

This way we can avoid all problems now and in the future as /usr/local/ is never touched by anything from OS/distribution.

**Comment by lots0logs** [comment]
@Grimeton Now that 20.04 is the current LTS this issue is going to hit many more people wasting countless hours. If no one has time to fix it then can we at least update the README.md with the workaround?

**Comment by Grimeton** [comment]
Well, thanks to Corona I didn't really have a lot to do, so I wrote my own init system...

Problem solved ;-P

**Comment by jprjr** [comment]
The workaround has been in the README since April 2016.

https://github.com/just-containers/s6-overlay#bin-and-sbin-are-symlinks

**Comment by lots0logs** [comment]
Sure but can we agree that considering the most widely used distribution now uses symlinks as described the workaround should be more prominently placed in the README than it is currently?

**Comment by jprjr** [comment]
Send a pr and I'll likely accept it.

Honestly considering shutting down my GitHub account.

On May 3, 2020 10:01:46 PM EDT, Dustin Falgout <notifications@github.com> wrote:
>Sure but can we agree that considering the most widely used
>distribution now uses symlinks as described the workaround should be
>more prominently placed in the README than it is currently?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/just-containers/s6-overlay/issues/288#issuecomment-623226385

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lots0logs** [comment]
@jprjr Done :heavy_check_mark: 

https://github.com/just-containers/s6-overlay/pull/294
