### ISSUE TITLE
README: "Logging" section does not say how to set permissions

### ISSUE THREAD

**Issue by wwoods** [just-containers/s6-overlay#291]
Following the example on https://github.com/just-containers/s6-overlay , `logutil-service` just throws errors:

    s6-envuidgid: fatal: unable to exec s6-applyuidgid: Permission denied

This is likely because the s6-envuidgid has inaccessible permissions to nobody.  Running `chmod a+x /bin/s6*` resulted in this:

    s6-applyuidgid: fatal: unable to set supplementary group list: Operation not permitted

Clearly, it is non-trivial to get the logutil-service working as specified in the initial README, which is confusing for a new user like myself.

**Comment by jprjr** [comment]
Can you provide an example Dockerfile that does this?

**Comment by wwoods** [comment]
https://gist.github.com/wwoods/c1eeb5f571f4f02f4e12b02633806aa6

As far as I can tell, that follows the instructions.  Again, the purpose of this issue is that there weren't clear instructions.

**Comment by jprjr** [comment]
The reason for the `s6-envuidgid` error is because of calling `s6-setuidgid mongodb` within the `log/run` script.

It's already switched to the `mongodb` user, but then `logutil-service` tries to switch to the `nobody`.

Now, removing the call to `s6-setuidgid mongodb` still presents an error (but it's a bit more obvious: `s6-log: fatal: unable to mkdir /var/log/mongodbz: Permission denied`).

`s6-log` will try to create the `/var/log/mongodbz` directory if it doesn't exist. Since this is done after switching to the `nobody` user, it gets the "permission denied" error.

I usually use scripts in `cont-init.d` to create my logging directories when the container starts, I'll add something to the readme about that.

**Comment by jprjr** [comment]
Here's an example Dockerfile that creates the log directory:

```
FROM ubuntu:18.04

RUN \
    apt-get update \
    && apt-get install -y mongodb

ADD https://github.com/just-containers/s6-overlay/releases/download/v1.21.8.0/s6-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C /

# Setup service files to automatically run mongodb in the background
# and log using s6-overlay's logutil-service
RUN \
    mkdir -p /data/db \
    && mkdir -p /etc/cont-init.d \
    && echo "#!/bin/sh" > /etc/cont-init.d/mongodb-log \
    && echo "mkdir -p /var/log/mongodbz" >> /etc/cont-init.d/mongodb-log \
    && echo "chown -R nobody:nogroup /var/log/mongodbz" >> /etc/cont-init.d/mongodb-log \
    && chmod +x /etc/cont-init.d/mongodb-log \
    && mkdir /etc/services.d/mongod \
        && echo "#! /usr/bin/with-contenv /bin/sh\nmongod >/dev/null 2>/dev/null" >> /etc/services.d/mongod/run \
        && chmod a+x /etc/services.d/mongod/run \
        && mkdir /etc/services.d/mongod/log \
        && echo "#!/usr/bin/execlineb -P\nlogutil-service /var/log/mongodbz" >> /etc/services.d/mongod/log/run \
        && chmod a+x /etc/services.d/mongod/log/run

ENTRYPOINT ["/init"]
```

**Comment by wwoods** [comment]
Thanks for giving an example, and amending the docs for next time.  Much appreciated.
