### ISSUE TITLE
Question: /etc/s6/services/s6-fdholderd/supervise: No such file or directory starting with v2.1.0.0

### ISSUE THREAD

**Issue by adobejmong** [just-containers/s6-overlay#311]
Hello,

We are upgrading from s6-overlay (https://github.com/behance/docker-base/commit/c33338236c1082b9d39b9ce8ddf25f849ec3e48d) from `v2.0.0.1` [1] to `v2.1.0.2` [2] and I'm trying to track down when and why `./etc/s6/services/s6-fdholderd/supervise/` was removed. 

I've gone back to the commit history for s6-overlay and poked around the s6 git repo but I'm unable to figure out why it was removed.

From what I can tell, the switch happened between 2.0.0.1 and 2.1.0.0 [3] but I did not see anything material in the changelog notes.

v2.0.0.1:
```
$ tar -ztvf /tmp/v2.0.0.1.tar.gz | grep 's6-fdholderd'
-rwxr-xr-x  0 root   root    95392 May 12  2020 ./bin/s6-fdholderd
[...snip...]
-rwxr-xr-x  0 root   root      121 May 13  2020 ./etc/s6/services/s6-fdholderd/run
-rw-r--r--  0 root   root        1 May 13  2020 ./etc/s6/services/s6-fdholderd/notification-fd
drwx------  0 root   root        0 May 13  2020 ./etc/s6/services/s6-fdholderd/supervise/
-rw-rw-r--  0 root   root        1 May 13  2020 ./etc/s6/services/s6-fdholderd/down
```

v2.1.0.0
```
$ tar -ztvf /tmp/v2.1.0.0.tar.gz | grep 's6-fdholderd'
-rwxr-xr-x  0 root   root    95392 May 12  2020 ./bin/s6-fdholderd
[...snip...]
-rwxr-xr-x  0 root   root      121 Sep 12 16:09 ./etc/s6/services/s6-fdholderd/run
-rw-r--r--  0 root   root        1 Sep 12 16:09 ./etc/s6/services/s6-fdholderd/notification-fd
-rw-rw-r--  0 root   root        1 Sep 12 16:09 ./etc/s6/services/s6-fdholderd/down
```

Was the removal of the `supervise` folder on purpose or just oversight? If it was on purpose, I would appreciate a pointer if you have one.

Thanks in advance

[1] https://github.com/just-containers/s6-overlay/releases/tag/v2.0.0.1
[2] https://github.com/just-containers/s6-overlay/releases/tag/v2.1.0.2
[3] https://github.com/just-containers/s6-overlay/releases/tag/v2.0.0.1 vs https://github.com/just-containers/s6-overlay/releases/tag/v2.1.0.0

**Comment by dreamcat4** [comment]
@glerchundi we need you again! You made all those many repos / build scrips far to difficult to follow along.

Anoher questin: how to find where the symlink came from in `/bin/execlineb` because that overwrites the other (real) `/usr/bin/execlineb after unpacking the archive, It remains a mystery for everybody else.

**Comment by jprjr** [comment]
That was intentional, for adding `USER` support.

So when running with `USER` you basically have to use a read-only root filesystem and copy everything you `/var/run/s6`. Issue was, `/etc/s6/services/s6-fdholderd/supervise` is owned by `root` and has `0700` permissions, so copying it in would fail.

Instead `init-stage1` just creates it at run-time, here: https://github.com/just-containers/s6-overlay/pull/305/files#diff-fcf8c9698741d64d659bdefde28f36cd1207160d87e4bd2a89b0a1baa29de417

@adobejmong did this change break anything?

@dreamcat4 the latest releases offer a self-extracting executable that will do the right thing with `/bin/execlineb`

**Comment by jprjr** [comment]
Oh I see the issue, I didn't add that same logic to the catchall version of init-stage1. Fixing now.

**Comment by jprjr** [comment]
This is the latest build from master, let me know if it fixes the issue and I'll tag a release

[s6-overlay-amd64.tar.gz](https://github.com/just-containers/s6-overlay/files/5578206/s6-overlay-amd64.tar.gz)

**Comment by adobejmong** [comment]
Thank you @jprjr : This looks good. Please release whenever you have time. Much appreciated!
