### ISSUE TITLE
How to prefix logs to stdout?

### ISSUE THREAD

**Issue by marrold** [just-containers/s6-overlay#318]
Hi,

I have a single container running several processes that are logging to stdout. This results in the lines in `docker logs` being mixed per process. Is it possible to add a prefix? I tried piping into `sed` but then no logs appeared at all, and its not clear if `s6-logs` can add a prefix and output on `stdout` for consumption via the docker logging driver.

Is there also a way to filter empty log lines? 

Thanks

**Comment by jprjr** [comment]
I've got an example of that here: https://github.com/just-containers/s6-overlay/issues/304

`s6-log` won't log to stdout, it just logs to files.

I believe GNU sed buffers data by default which may be why you're not seeing anything. You may need to use the `--unbuffered` switch.

**Comment by tennox** [comment]
With s6-rc.d format it got quite a bit more complicated (no `log/run`), but I found an easy solution :
```execlineb
#!/command/execlineb -P
fdmove -c 2 1 # redirect stderr into stdout
pipeline -w { sed --unbuffered "s/^/[service1] /" }
exec service1
```
(note: uses gnused, with busybox' sed it did not work :tipping_hand_man:)
docs: https://skarnet.org/software/execline/pipeline.html

@jprjr does this make sense? or am I doing a mistake?

**Comment by skarnet** [comment]
This will nominally work (you should also be able to use busybox's `sed` if you remove the `--unbuffered` option, bb sed shouldn't buffer anyway). Note that in execline, you don't need the `exec` command before `service1`.

However, if for some reason your `sed` program dies, you will lose your logs until your service restarts.

A better solution would be to do the pipeline in the *logger* script, something like
```
#!/command/execlineb -P
pipeline { sed "s/^/[service1] /" }
s6-log ...
```
because if `sed` dies then s6-log will notice and die too, and the whole logger service will restart.

An even better solution, but more complex, is to use the power of the s6-rc pipelining mechanism: put the `sed` command in its own service, `service1-sed`, that is the consumer for `service1` and a producer for `service1-log`. In other words, instead of having a `service1 | service1-log` pipeline, make a `service1 | service1-sed | service1-log` pipeline.

Or you can wait for the next version of s6 and s6-overlay, which should drop in a month or so, and  s6-log will have support for prefixes. :-)
