### ISSUE TITLE
Terminating a Docker container with 1 process takes > 10 sec

### ISSUE THREAD

**Issue by bmccorm2** [just-containers/s6-overlay#331]
I'm frustrated at the time it takes my container to shut down when using the S6 overlay service. As far as i understand, s6 should run as PID 1 and should issue the SIGTERM to all children processes (postfix in my example) when you issue `docker stop`. I confirmed it is running as PID 1 but still takes 10sec to stop. I tried with Tini init system and it closes instantaneously. What am i doing wrong here?

```
Dockerfile

FROM ubuntu:latest

# Add S6 Overlay
ADD https://github.com/just-containers/s6-overlay/releases/download/v2.2.0.1/s6-overlay-amd64-installer /tmp/
RUN chmod +x /tmp/s6-overlay-amd64-installer && /tmp/s6-overlay-amd64-installer /

# Add S6 Socklog
ADD https://github.com/just-containers/socklog-overlay/releases/download/v3.1.1-1/socklog-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/socklog-overlay-amd64.tar.gz -C /

ARG TZ=America/Denver
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone

RUN ["/bin/bash", "-c","debconf-set-selections <<< \"postfix postfix/mailname string test.com\""] && \
    ["/bin/bash", "-c","debconf-set-selections <<< \"postfix postfix/main_mailer_type string 'Internet Site'\""]

RUN apt update && \
    apt upgrade -y && \
    DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends \
        postfix && \
    apt -y autoremove && \
    apt -y clean autoclean && \
    rm -drf /var/lib/apt/lists/* /tmp/* /var/tmp /var/cache

ENTRYPOINT ["/init"]
CMD [ "postfix", "start-fg" ]
```
Build the Image: `docker build -t test .`

Run the Image: `docker run --name test --rm -d test`

Stop the Image: `docker stop test`

**Comment by nigelgbanks** [comment]
In the [README,md](https://github.com/just-containers/s6-overlay/blob/master/README.md) there are a number of `GRACETIME`  environment variables with defaults that would likely explain the time taken.

- `S6_SERVICES_GRACETIME` defaults to 3 seconds
- `S6_KILL_GRACETIME` defaults to 3 seconds

And since your using the `CMD` feature `S6_CMD_WAIT_FOR_SERVICES_MAXTIME` which is 5 seconds.

In total that would be around 10 seconds.

**Comment by nigelgbanks** [comment]
I haven't really used that plugin so I can't say

**Comment by bmccorm2** [comment]
Ok thanks.....now that i know the source of the problem I will move this issue to the socklog overlay repo.

**Comment by alexyao2015** [comment]
@bmccorm2 I experienced the same issue here and noticed that it not in v2.1.0.2 and below. It appears that with newer versions, SIGTERM blocking has been implemented properly in s6. For example, a service running `s6-pause -th` should block SIGTERM and thus not be able to be killed by s6. In previous versions, it seemed to not respect it and thus would kill the container immediately. In your case, you would need to ensure that all services logging to syslog during container shutdown are killed using a finish script, so that socklog can properly terminate since it will sit and keep the container alive until all services logging to syslog are dead.

In my case, I had apache running but had not included a container finish script to stop it. Since socklog which is using s6-log -p has not received an EOL, it will not allow the container to terminate. Thus, the container is finally terminated when Docker forcefully terminates it.

This is a not very well-known peculiarity and should be better documented. Initially, I had thought this was a bug as well, but after extensive testing, I realized that the issue was due to this peculiarity.

**Comment by bmccorm2** [comment]
@alexyao2015 You're totally right with v2.1.0.2.  Mine terminates quickly with that version.  However, I still wasn't able to get it to work with the current version.  Do you know if i need something else in my finish script? (I simplified my docker image to use the example on their github page - nginx - it has the same issue)

Dockerfile
```
FROM ubuntu
ADD https://github.com/just-containers/s6-overlay/releases/download/v2.2.0.3/s6-overlay-amd64-installer /tmp/
RUN chmod +x /tmp/s6-overlay-amd64-installer && /tmp/s6-overlay-amd64-installer /

# Add S6 Socklog
ADD https://github.com/just-containers/socklog-overlay/releases/download/v3.1.1-1/socklog-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/socklog-overlay-amd64.tar.gz -C /

RUN apt-get update && \
    apt-get install -y nginx && \
    echo "daemon off;" >> /etc/nginx/nginx.conf

COPY ./services /etc/services.d

ENTRYPOINT ["/init"]
```

Finish Script
```
#!/bin/sh
s6-svscanctl -t /var/run/s6/services
```

Run Script
```
#!/usr/bin/with-contenv sh
exec nginx
```

**Comment by alexyao2015** [comment]
@bmccorm2 You need to terminate nginx in your finish script. I.e. Run `nginx stop` in your finish script.

**Comment by bmccorm2** [comment]
I've tried that as well.  It still terminates in 10 sec :/

**Comment by alexyao2015** [comment]
Try pkill. You simply just need to ensure all processes logging to socklog are terminated during container shutdown. If its taking 10 seconds, it may be because something else is causing it to hang.

**Comment by alexyao2015** [comment]
I had noticed that docker stop works normally once all services are stopped, but if a service that should take down the container crashes, the container does not stop automatically unless socklog is killed with a SIGKILL. In my case, I simply added `killall -9 socklog` to my finish script of the service that should take down the container.

**Comment by bmccorm2** [comment]
Ok thanks for the clarification.  I've been playing around and socklog is definitely the problem.  I make sure i kill that in my finish script and now container stops in 3 secs.  Then i said S6_KILL_GRACETIME=100 and now the container stops instantly.  So all is good now thanks for your help.

Just a general question though: I feel like i had to cobble together a hack to get this to close quickly. I thought the purpose of S6 was that S6 was PID1 and sends KILL signals to child processes (i.e., nginx and socklog).  Now I am doing that, in addition to that env variable.  Just doesn't seem right.  Or am i just whining :)

**Comment by alexyao2015** [comment]
I would highly suggest not setting S6_KILL_GRACETIME to 100. That doesn't give the processes time to stop. 
S6 sends term signals which are blocked by the services themselves. After a timeout, it them sends a KILL signal.

**Comment by bmccorm2** [comment]
If i take that out the container will stop in 3 sec.  Is that the expected behavior?  (I'm pretty sure i am stopping all services)

Finish: 
```
#!/bin/sh
pkill -9 nginx
pkill -9 socklog
killall -9 nginx
killall -9 socklog
```
