### ISSUE TITLE
CentOS and overwriting files in /bin

### ISSUE THREAD

**Issue by rbro** [just-containers/s6-overlay#336]
The below items haven't caused me any problems, but I was curious if they could be potential issues.

I am running s6-overlay in both CentOS 7 and CentOS 8.  I noticed that when I extract s6-overlay-amd64.tar.gz, it overwrites these 3 files:

/bin/cd
/bin/umask
/bin/wait

These 3 files come from the RPM for bash.

1) I haven't run into anything specific, but could this create issues for CentOS since s6-overlay is overwriting the CentOS-supplied files for these commands?

2) Similar to issue #278, if I install an updated RPM of bash, it will overwrite these 3 files back to the CentOS-supplied files, and the s6-overlay-supplied files would no longer exist.  Would this create issues with s6-overlay?

To be safe, would it be possible to have s6-overlay not overwrite these files and instead use unique filenames, or would that be a larger change?

Thank you for your help.

**Comment by skarnet** [comment]
Sorry for the delay in answering.

You wouldn't have had any problems because nothing ever uses these commands on CentOS: when you invoke them from a shell, the shell uses its builtins. The commands only exist because POSIX mandates them; as standalone binaries, they're utterly useless.
execline commands, which replace them, work in a different way and it makes sense for them to be present in the filesystem.

Nevertheless, in version 3.0.0.0 of s6-overlay, which is out now, the overlay installs its commands in a completely different place, so it never overwrites anything on your image. Your concerns can finally be laid to rest. ;-)
