### ISSUE TITLE
Single Process Containers

### ISSUE THREAD

**Issue by michaelaguiar** [just-containers/s6-overlay#351]
Quick question: Are there any benefits of using s6 in a container with a single process (php-cli for example), or is it best to only use in containers that run multiple processes (php-fpm + Nginx)?

Thanks!

**Comment by skarnet** [comment]
By definition, a single process container cannot use s6, because s6 involves multiple processes. If you want to run a single process container, you will just run your daemon as this single process - it will be pid 1 in its container.

What you are probably referring to are single _service_ containers, where the container only provides one functionality, which may or may not involve more than one process. And for some single _service_ containers, then yes, s6 can be beneficial, because it allows you to control your service in a more comfortable way than a single-process container would - you can set up in-container logging, for instance.

In the end, it's a choice you have to make: are the benefits or using something like the s6 infrastructure worth it for a single service? Only you can answer this question.

**Comment by michaelaguiar** [comment]
Excellent response! This answers my question and makes it a bit more clear how I should design base images.
