### ISSUE TITLE
Graceful termination of CMD process

### ISSUE THREAD

**Issue by eddienko** [just-containers/s6-overlay#356]
I would like to perform graceful termination of the CMD command and I cannot manage to do it. I have a usual docker image with

```
ENTRYPOINT ["/init"]
```

That I run as

```
docker run --rm -it myimage /usr/local/bin/testprogram.py
```

where `/usr/local/bin/testprogram.py` is

```
#!/opt/conda/bin/python

import signal
import time

run = True

def handler_stop_signals(signum, frame):
    global run
    print("RECEIVED", signum)
    run = False

def hup(signal, frame):
    print('RECEIVED HUP')

signal.signal(signal.SIGINT, handler_stop_signals)
signal.signal(signal.SIGTERM, handler_stop_signals)
signal.signal(signal.SIGHUP, hup)

while run:
    pass

print('Exit 1')
time.sleep(10)
print('Exit 2')
```

# Scenario 1

I run the docker container as above and I hit 'Ctrl-C', then I get:

```
[services.d] starting services
[services.d] done.
^CRECEIVED 2
Exit 1
Exit 2
[cmd] /usr/local/bin/testprogram.py exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

# Scenario 2

I run the docker container as above and then I stop it with `docker stop`:

```
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
RECEIVED HUP
RECEIVED 15
Exit 1
[s6-finish] sending all processes the KILL signal and exiting.
```

So the CMD program gets a HUP and then a TERM, and then it is killed before termination after all the cont-finish and s6-finish scripts are done.

I can use `S6_KILL_GRACETIME=60000` here so that CMD runs until the end, but then then container does wait 60s to terminate instead of then 10s that it takes CMD to finish.

# What I would like

I would like that when stopping the container, CMD is terminated before cont-finish starts. I.e. that `docker stop` mimics what happens when you hit `ctrl-C`. Is that possible at all?

**Comment by skarnet** [comment]
Unfortunately, due to the design of `docker stop`, it's not possible.

However, in the v3 version of s6-overlay, that will be released very soon, there will be a way to achieve that: instead of `docker stop`, you can run
`docker exec kill $(cat /run/s6-linux-init-container-results/pid)`
and that will kill your `CMD` first, then the container will shut down.

Sorry for the delay in answering; I hope the solution in v3 will be applicable for you.

**Comment by skarnet** [comment]
So, in order to keep ^C working as intended, unfortunately I could not implement the `/run/s6-linux-init-container-results/pid` thing. So if you want to terminate CMD, you will have to enter the container via `docker exec` and find the CMD's pid yourself, then kill it - then the container will exit gracefully.

I'm sorry I don't have a better solution. Can I close this?

**Comment by eddienko** [comment]
Thanks for spending time on this. I will have a look at your solution.
