### ISSUE TITLE
[Question] run script not executing

### ISSUE THREAD

**Issue by andrewmiskell** [just-containers/s6-overlay#384]
I'm building out a new container using the new 3.0 version but I'm having trouble even getting a basic oneshot service to execute.

Container is Alpine Edge (i386 arch) with the i686 arch version of s6-overlay.

I have a very simple service I'm starting out with to adjust and set UID/GID for a user.

```
/etc/s6-overlay/s6-rc.d/10-adduser # cat run
#!/command/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

/usr/sbin/groupmod -o -g "$PGID" abc
/usr/sbin/usermod -o -u "$PUID" abc

chown abc:abc /app
chown abc:abc /config

touch /tmp/10-adduser
```

I have all the files in the correct place per the documentation (run, up, type along with 10-adduser in user/contents.d) and when I start the container it says that the service started successfully, but nothing actually happened.

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 10-adduser: starting
s6-rc: info: service 10-adduser successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
```

The UID/GID doesn't change and there's no /tmp/10-adduser file created (that's just there to see if the script actually worked).

Am I missing something basic here?

**Comment by andrewmiskell** [comment]
I also noticed that if you down have an up script (even if blank) s6-rc-compile fails and hangs the container start. Adding a blank up file to the service directory corrects the issue.

```
❯ docker run -it twgs-docker /bin/bash
WARNING: The requested image's platform (linux/386) does not match the detected host platform (linux/amd64) and no specific platform was requested
s6-rc-compile: fatal: unable to open /etc/s6-overlay/s6-rc.d/10-adduser/up: No such file or directory
```

**Comment by skarnet** [comment]
s6-rc oneshots don't work that way.
- oneshots don't use a `run` script, but `up` and `down` scripts. Your `run` file is simply being ignored, and since you have no `up` or `down` file in the source definition directory, your `10-adduser` service is doing nothing.
- `up` and `down` files can't be written with a shebang - they have to use execline syntax. You don't have to bother with details of this syntax - you can just put your script somewhere else and call it from `up`.

Concretely, to make your service work:
- Move your `/etc/s6-overlay/s6-rc.d/10-adduser/run` file to `/etc/s6-overlay/scripts/10-adduser` and make it executable
- Write
```
/etc/s6-overlay/scripts/10-adduser
```
to `/etc/s6-overlay/s6-rc.d/10-adduser/up`

and then s6-rc will call `/etc/s6-overlay/scripts/10-adduser` when it brings up the service, which should do what you want.

**Comment by andrewmiskell** [comment]
Did what you suggested, it's attempting to run the script now, but I'm getting this on startup.

```
s6-rc-oneshot-run: fatal: unable to exec /etc/s6-overlay/scripts/10-adduser: Exec format error
```

I've confirmed that the script is executable and it run without issue when run manually. Is there something I'm missing from the up script?

**Comment by skarnet** [comment]
That's pretty weird, it should work. You're not missing anything from the s6-rc setup; the error comes from the kernel not being able to interpret the `#!/command/with-contenv` shebang, which is itself a script invoking the `/command/execlineb` binary - which should be working since your container booted.

Are you mix-and-matching binaries and packages? x86_64 binaries won't work on i686, and i686 binaries will only work on x86_64 machines if the kernel has a specific option enabled.

**Comment by andrewmiskell** [comment]
Nevermind, it's working. It was docker caching causing the problem and it wasn't copying the updated script.

Thanks! I'll keep the difference between oneshot and longrun in mind for the future.

**Comment by skarnet** [comment]
Excellent! Closing this then.
