### ISSUE TITLE
Binary not found in PATH when using with-contenv

### ISSUE THREAD

**Issue by Jeiwan** [just-containers/s6-overlay#388]
Hi!

I'm getting this error when trying to run a service that worked fine on version 2:
> ./run: 7: java: not found

My Dockerfile:
```Dockerfile
FROM adoptopenjdk:8-jre

ARG S6_OVERLAY_VERSION=3.0.0.2

RUN apt-get update -q && \
    apt-get install -y --no-install-recommends xz-utils && \
    rm -rf /var/lib/apt/lists/*

ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch-${S6_OVERLAY_VERSION}.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-noarch-${S6_OVERLAY_VERSION}.tar.xz
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64-${S6_OVERLAY_VERSION}.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-x86_64-${S6_OVERLAY_VERSION}.tar.xz

COPY etc/s6-overlay/s6-rc.d/ /etc/s6-overlay/s6-rc.d/

ENTRYPOINT ["/init"]
```

Script:
```shell
#!/command/with-contenv sh

java -version
```

PATH in the container:
```
root@2a943b39aa0e:/# echo $PATH
/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@2a943b39aa0e:/# which java
/opt/java/openjdk/bin/java
```

Full log:
```
s6-rc: info: service envcheck: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service envcheck successfully started
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
./run: 3: java: not found
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
./run: 3: java: not found
./run: 3: java: not found
./run: 3: java: not found
...
```

This is a workaround that I've ended up using:
```shell
#!/command/with-contenv sh

PATH=/opt/java/openjdk/bin:$PATH
java -version
```

**Comment by skarnet** [comment]
Fixed in git already; we'll release a new version soon.

**Comment by skarnet** [comment]
Sorry, I had misdiagnosed the problem, which is why I made an inaccurate comment and closed the issue (which I will still do, but not before you've read my answer 😅)

The thing is that it's *always* a mistake to import PATH from the host environment. It's not safe at all. To prevent that, s6-overlay v3.0.0.2 and later remove PATH from the list of imported variables, on purpose.

By default, your services are started with a `/command:/usr/bin:/bin` PATH. With the current version, 3.0.0.2, you can change it by modifying the `/etc/s6-overlay/config/global_path` variable; but users have reported that it wasn't a practical way of configuring it, so in the incoming version, 3.1.0.0 which will be out early this week, the global path is read from the `S6_GLOBAL_PATH` container variable instead - you can declare it in your Dockerfile.

That said, your workaround isn't a workaround at all: it's the correct fix. Adapting the PATH to the needs of each service is the secure way of proceeding, and if the rest of your services are working, I encourage you to keep the PATH modification local to your java invocation. And it will work with 3.0.0.2 as well as 3.1.0.0 and hopefully any future version.

(Please `exec` your java invocation, though, so you don't have a shell staying around and intercepting signals from the supervisor.)

**Comment by Jeiwan** [comment]
@skarnet Thanks for clarifying this! And thanks for the `exec` hint.
