### ISSUE TITLE
Environment variable S6_STAGE2_EXITED is not set anymore

### ISSUE THREAD

**Issue by felipecrs** [just-containers/s6-overlay#406]
It used to be set in v2, so that I could do something like this in `/etc/cont-finish.d/99-message.sh`:

```bash
#!/usr/bin/env bash
if [[ "${S6_STAGE2_EXITED}" -ne 0 ]]; then
  echo "Container failed"
fi
```

I didn't see this removal documented anywhere, so I wonder if it was a mistake or what.

If it wasn't a mistake, how do I achieve the same result now?

**Comment by skarnet** [comment]
Hmm, I wasn't aware the previous version (which I didn't write, and only reviewed a long time ago) was *setting* environment variables to be consulted by scripts. This doesn't match with the main way s6-overlay uses variables, i.e. as *user-configurable inputs*. I will take a closer look at how v2 operates.

In v3, the `rc.init` script will definitely tell you (on the container's stderr) if it failed; user scripts are not really supposed to depend on the container's execution path. However,  there's a slightly hacky way of achieving what you want: if you have a down script (or a script in `/etc/cont-finish.d`) that needs to know whether the container succeeded or failed, you can read the `/run/s6-linux-init-container-results/exitcode` file, which contains the exit code of the last important command that was executed. If it's 0, it's a success, otherwise it's a failure.

If s6-rc failed to start all the services and the `S6_BEHAVIOUR_IF_STAGE2_FAILS` variable is 2 or more, then `/run/s6-linux-init-container-results/exitcode` contains the s6-rc exit code and the container exits right away, but your `/etc/cont-finish.d` scripts will still be run unless the error occurred in `/etc/cont-init.d`.

If s6-rc managed to start all the services and you have a CMD, then `/run/s6-linux-init-container-results/exitcode` will contain the exit code of your CMD. If you have no CMD, then the file isn't set, but you shouldn't care since the container should only stop when told to via a `docker stop` command.

**Comment by felipecrs** [comment]
Thank you for the rationale. I can almost replace the `S6_STAGE2_EXITED` with `/run/s6-linux-init-container-results/exitcode`, but how to make `cont-finish` run even when `cont-init` fails like before?

**Comment by felipecrs** [comment]
As always, thanks for the explanation. Option 2 sounds very reasonable, and I'll look into converting my services to the new format instead of working around using option 1. The v3 already brought several "breaking changes", so this would be just one more. 😃
