### ISSUE TITLE
Any tips for a cleanup (`cont-finish.d`) script which requires a supervised service up?

### ISSUE THREAD

**Issue by felipecrs** [just-containers/s6-overlay#418]
Let's say I have a `/etc/services.d/dind/run` which keeps the docker daemon up (in a docker in docker image).

I want to create a cleanup script `/etc/cont-finish.d/dind.sh` which will:

```bash
#!/bin/bash

docker ps --all --quiet | xargs --no-run-if-empty -- docker rm --force
```

But it requires the `dind` service to be up, which may not be the case since s6-overlay calls `cont-finish.d` after the services shutdown has already started.

So, I thought on this:

```bash
#!/bin/bash

set -euo pipefail

# Ensure bash will not leave any background processes running
trap 'kill 0' EXIT

echo "Waiting for dind to be stopped by s6-svc..." >&2
s6-svwait -D /var/run/s6/services/dind

echo "Starting dind again..." >&2
dind dockerd &

# Wait until dockerd is ready.
until docker ps >/dev/null 2>&1; do
    sleep 1
done

echo "Cleaning up..." >&2
docker ps --all --quiet | xargs --no-run-if-empty -- docker rm --force
```

But I think it's far from ideal. Any tips?

**Comment by skarnet** [comment]
You need to run a script at shutdown while your dind service is still up?

Make a s6-rc oneshot, with an empty `up` file, and the path to your script in the `down` file. Add this oneshot to the contents of the `user` bundle.
At boot time, s6-rc will start this service, which does nothing; at shutdown time, it will stop it, which will call your cleanup script. And since the s6-rc user services are started after the `/etc/services.d` ones and stopped before them, you can be certain that your script will be called before dind is stopped.

**Comment by felipecrs** [comment]
Wow, okay, that's fortunate for me! I will try it. Thank you very much, sir!
