### ISSUE TITLE
Read only mode difficult to work with when writable directory is not /run

### ISSUE THREAD

**Issue by edevil** [just-containers/s6-overlay#450]
s6 can work in a mostly read-only mode, but it requires `/run` to be writable. In my environment the only writable directory is `/tmp`.

I attempted to work around this by creating a symlink `/run` -> `/tmp`, but then s6 **also** requires /var/run to be a symlink pointing to /run, for some reason. The way this check is being done at the moment ends up finding that /var/run -> /run -> /tmp and tries to delete `/var/run`, which of course fails.

Is /var/run really needed to s6 to work? If so, the check should be relaxed so that this symlink succession works.

**Comment by skarnet** [comment]
`/var/run` isn't strictly necessary in v3, but is enforced as a symlink to `/run` for compatibility with v2 images.

But regardless of that, unfortunately, your setup is not and cannot be supported. s6-overlay wants `/run` to be writable and distinct from `/tmp`, and that's an absolute requirement; if you use `/tmp` as a `/run`-equivalent, your image will be vulnerable to DoS and privilege gain attacks.

(The fundamental difference is that `/tmp` is writable by normal users, whereas `/run` is only writable by root - or, in s6-overlay's case, the container's owner.)

If you can only have one tmpfs, please at least separate it into `/mnt/tmpfs/run` with rights 0700, and `/mnt/tmpfs/tmp` with rights 01777, and appropriate `/run` and `/tmp` symlinks. It will not be ideal (still vulnerable to some DoS attacks if users fill out the tmpfs) but it will be better than storing vital system files in `/tmp`.

**Comment by edevil** [comment]
I understand your point, this is definitely not the situation I would like to be in but these are currently my constraints.

Your suggestion would still fail on my original point though, the /var/run check prevents /run from being any kind of symlink.

**Comment by skarnet** [comment]
Yes, because the only fully secure setup is `/run` being its own tmpfs. My suggestion *mitigates* the main issue (no predictable file name attack) but does not *solve* it (users can still DoS the system). It might be an acceptable trade-off for you, in which case I encourage you to apply your patch to your copy of s6-overlay, but for us as upstream, it's not.

I'll probably relax the checks a bit in a (near) future version, because you're right that not having `/run` as the mountpoint itself is valid (if for instance `/run` is a symlink to the real mountpoint under `/mnt` or something) - but it will be accompanied by more checks, and warning messages if things don't look fully secure. Your change as submitted is just too permissive to be integrated upstream.

**Comment by edevil** [comment]
Thank you for the follow up. 

I just have one last question. In order to setup the writable directory under /tmp is there some hook that I can use in the startup sequence to run a script of mine? It needs to run before the checks. Or do I have to supply my own entrypoint, and then pass execution to /init after creating the dir structure/symlinks?

**Comment by skarnet** [comment]
Ideally you should be able to configure your container management system to prepare everything for you. Apart from that, I'm afraid I have no better solution than supplying your own entrypoint. s6-overlay was voluntarily designed with a very limited set of hooks, in order to have as reliable and reproducible boot sequences as possible.
