### ISSUE TITLE
Logging doesn't appear to be working

### ISSUE THREAD

**Issue by ambled** [just-containers/s6-overlay#479]
I have setup an s6-rc process for redis, however the log paths are not being created (if I run the log/run script manually, the log contructs are created). In addition, the redis startup output is showing up in the docker logs instead of being piped through s6-log.

What could I be missing?

Dockerfile
```
FROM amazonlinux:2 AS base
ARG S6_OVERLAY_VERSION=v3.1.1.2
# Adding S6-overlay to manage container services
RUN wget https://github.com/just-containers/s6-overlay/releases/download/${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz --no-check-certificate -O /tmp/s6-overlay-x86_64.tar.xz \
    && wget https://github.com/just-containers/s6-overlay/releases/download/${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz --no-check-certificate -O /tmp/s6-overlay-noarch.tar.xz \
    && tar xpJf /tmp/s6-overlay-noarch.tar.xz -C / \
    && tar xpJf /tmp/s6-overlay-x86_64.tar.xz -C / \
    && rm -f /tmp/s6-overlay-x86_64.tar.xz  \
             /tmp/s6-overlay-noarch.tar.xz

COPY docker/s6-overlay /etc/s6-overlay
RUN chmod +x /etc/s6-overlay/s6-rc.d/*/run \
             /etc/s6-overlay/s6-rc.d/*/log/run

```

/etc/s6-overlay/s6-rc/redis/run
```
#!/command/with-contenv bash
exec /usr/bin/redis-server /home/local/redis.conf --daemonize no 2>&1
````
/etc/s6-overlay/s6-rc/redis/type
```
longrun
```

/etc/s6-overlay/s6-rc/redis/log/run
```
#!/command/execlineb -P
/command/s6-log /var/log/redis
```
/etc/s6-overlay/s6-rc/redis/log/type
```
longrun
```
/etc/s6-overlay/s6-rc/user/contents.d/redis exists

**Comment by skarnet** [comment]
`log` subdirectories don't work with s6-rc: all services must be declared at the same level.

Instead of `/etc/s6-overlay/s6-rc/redis/log`, put all your log service definition into `/etc/s6-overlay/s6-rc/redis-log`, then create a `/etc/s6-overlay/s6-rc/redis/producer-for` file containing `redis-log` and a `/etc/s6-overlay/s6-rc/redis-log/consumer-for` file containing `redis`. This way, you tell s6-rc that `redis` and `redis-log` are in a pipeline, which means that `redis` will send its output to `redis-log`.

**Comment by skarnet** [comment]
Closing this.
