### ISSUE TITLE
question: what would be the best way to activate a python venv in execlineb?

### ISSUE THREAD

**Issue by ehudkaldor** [just-containers/s6-overlay#490]
I know this is not the s6 repo, but i know @skarnet watches this, so i thought i might ask.

i need to activate a python venv before running my command. i know i can put it in a bash script and call it from `run`, but i wondered if there a more execline-native way to do that - call `. /venv/bin/activate` and push all it does to the environment that executes the next command?

**Comment by skarnet** [comment]
If `activate` is a piece of shell code that you need to source, then no, there's no other way than doing it in your shell. When a toolset is designed to be used with and within a shell, it's pretty hard to do without one.

If `activate` was only a list of `VAR=value` definitions, then you could use `envfile` to read it and execute into your program without spawning a shell; but it's probably not the case, since when you source it it has to *export* the variables and not only define them - so the syntax is likely not `envfile`-compatible.
