### ISSUE TITLE
Use local gcc on s390x

### ISSUE THREAD

**Issue by tseeling** [just-containers/s6-overlay#493]
I want to compile s6-overlay from scratch and use my internal gcc, not download a foreign binary package.
This is due to company and government constraints.
How can I do this?
Thanks.

**Comment by skarnet** [comment]
You can use a local toolchain by giving the `TOOLCHAIN_PATH=/path/to/your/toolchain/root` argument to your `make` invocation.

Note that your toolchain needs to support static linking, which may be troublesome if it's using glibc. s6-overlay is meant to be statically linked, in order to be entirely independent from the container.

Please be aware that we offer no support for builds that involve personalized toolchains. You may need to tweak the Makefiles in order to make it work; but you're on your own there.

**Comment by tseeling** [comment]
I was building s6-overlay 2.something last year and had it all sorted out, compiling all the dependencies and building the archive. We're running containers on s390x quite happily since then.

The build process for v3 is totally different, with includes that build the skalibs and everything depends on looking for $(ARCH)-gcc which I do not have at all - we're using Redhat's supplied gcc.
I'll try to adapt the Makefile(s). Thanks for the hint about justc-envdir, I wasn't aware it's no longer needed, I simply wondered why the latest package contains syntax errors.

**Comment by skarnet** [comment]
If you're using a native toolchain, you'll need to tweak the compiler invocations indeed, since s6-overlay was made for cross-compiling (including with a cross toolchain to the same arch!)

If you're using glibc, you'll need to remove the  `--enable-static-libc` option in `skaware.mk`.

Good luck!
