### ISSUE TITLE
Question: how do you implement a non-exiting, var-lasting `if` with S6?

### ISSUE THREAD

**Issue by ehudkaldor** [just-containers/s6-overlay#497]
@skarnet too

short, non-important background: i have an image the relies on Hashicorp vault for keys. it loops while it's waiting for the `secrets` file to appear, loads them as `env` files and continues the boot. 
but i also want a dev version, which does not rely on vault at all. the way i do that is to check if the vault id and key were provided as `env` vars, and if so, does the loop described above. otherwise, it skips it and uses the internal `env` params. it looks like this:
```
ifelse -n { test -z $VAULT_ROLE_ID$VAULT_SECRET_ID }
    # Then
    {
        foreground { printf "using vault. waiting for key file to be available\n" }
        foreground { loopwhilex -x 0 test -f /tmp/tmpfs/secrets/keys }
        envfile -i /tmp/tmpfs/secrets/keys
        foreground { printf "initializing\n" }
        foreground {
            ....../init.sh
            .........
    }
    # Else
    {
        foreground { printf "NOT using vault\n" }
        foreground { printf "initializing\n" }
        foreground {
            ....../init.sh
            .........
    }
}
```
two problems. the first leading to the second.
first problem is that the content of `envfile` does not survive outside of its block. so, doing this:
```

ifelse -n { test -z $VAULT_ROLE_ID$VAULT_SECRET_ID }
    # Then
    {
        foreground { printf "using vault. waiting for key file to be available\n" }
        foreground { loopwhilex -x 0 test -f /tmp/tmpfs/secrets/keys }
        envfile -i /tmp/tmpfs/secrets/keys
    }
    # Else
    {
        printf "NOT using vault\n"
    }
    foreground { printf "initializing\n" }
    foreground {
    ....../init.sh
    .........
}

```
is not possible.
which brings the second problem, which is that there is a lot of code duplication between the `if` and the `else`.

THE QUESTION:
is there a way to do an if that does not exit if with no else, that does exit of `if` being false, and the result of its `envfile` is then available outside the `if` block?

thank you.

**Comment by ehudkaldor** [comment]
addition:
i am aware of doing `envfile -I`. the problem is this is a oneshot doing the init, and it is depends on a longrun that keeps the key files fresh.

**Comment by skarnet** [comment]
First, `ifelse` does not take three blocks, but two: the "else" part is the remainder of the script. You are probably confusing it with `ifthenelse`.

Second, there is indeed no way for anything to persist beyond a closing brace. So, in your case, you would use `ifelse` and duplicate the rest of the command line in both options.

Third, since your initialization program seems to be written in shell, it means you're paying the price for a shell anyway, so I would write the whole piece of code as a shell script, which is probably simpler in this case. execline is best used for simple command lines that lead directly to your main program execution - as soon as you have to jump through hoops to do what you want, it's probably not worth using it instead of a shell.

Fourth, there is an exception to the second point above, but it is left voluntarily undocumented because I don't want people to abuse it, precisely because it breaks the rule that nothing survives a closing brace. If you decide to use this, I will offer no support for it, so use at your own peril:

`ifthenelse -s` will do the factorization you're asking for.
```
ifthenelse -s { your test }
{
  this-runs-if-true envfile something
}
{
  this-runs-if-false put-things-in-environment-and-execs
}
remainder
```

`remainder` will run with the environment you set in either block. Note that both blocks must `exec`, so your `printf` command above would need to be encapsulated in a `foreground` block.

I really would advise doing it in shell instead.

Good luck.

**Comment by ehudkaldor** [comment]
Ok the third point:
You might not remember, but I was the one who asked about `venv` a few weeks back, and had to take the bash route because if that. 
But that is because I have a (better be temporary) dependency on python 3.8 for a stupid reason. I did not even refactor truly - just commented out lines in the exceline script so I can set them free when I resolve matters.

So, I'll keep it frankenS6 for a while longer, with the hope of taking it back to pure.

As for `-s` - it sounds interesting and good to know, but I appreciate your guideline and will not use it unless the twins become too hard to manage.

Also,
I assume @jprjr is ok with me highjacking his repo to ask S6 questions, otherwise he would have said something. But if there's another place you prefer suck question, tell me.

**Comment by skarnet** [comment]
Well these are really execline questions. And they would be better asked on the [relevant mailing-lists](https://skarnet.org/lists/). I only use GitHub for issues and questions that are specific to s6-overlay.

**Comment by skarnet** [comment]
Closing this.
