### ISSUE TITLE
Wrong architecture gives s6-overlay-suexec error messages

### ISSUE THREAD

**Issue by mustanggb** [just-containers/s6-overlay#501]
Just encountered this and thought I'd document it for anyone else that has the same problem.
Yes it's quite obvious, but might help with someone's search engine lookup.

**Problem:**
init giving the following messages then exiting with code 2.
```
/command/s6-overlay-suexec: line 0: ?: not found
/command/s6-overlay-suexec: line 0: ?: not found
/command/s6-overlay-suexec: line 1:ELF: not found
/command/s6-overlay-suexec: line 2: syntax error: unexpected ")"
```

**Solution:**
Use the correct architecture files.
For example I was originally building against `amd64` with:
```
s6-overlay-noarch.tar.xz
s6-overlay-x86_64.tar.xz
```
But changed this to `arm64` and forgot to change to:
```
s6-overlay-noarch.tar.xz
s6-overlay-aarch64.tar.xz
```

**Comment by skarnet** [comment]
Thanks!

The tarballs use the gcc convention for architecture names: what is sometimes referred to as `amd64` (64-bit PC hardware) is called `x86_64`, what is sometimes referred to as `arm64` (armv8) is called `aarch64`, etc. The only exception is armv7, because soft-float and hard-float are two very different things; soft-float armv7 is named `arm`, and hard-float armv7 is named `armhf`.

Closing this since it's not an issue we should be working on, that shouldn't prevent search engines from doing their work.
