### ISSUE TITLE
Possible to use s6 for spawning/maintaining x number of processes?

### ISSUE THREAD

**Issue by intel352** [just-containers/s6-overlay#508]
I have a PHP cli script that runs to process messages from a message queue. I need to be able to run multiple instances of this message processor on a single deployment. I can't do this natively within PHP, since it's single-threaded, so the solution is to specifically spawn multiple copies of the same command/process.

With other process managers, this can be done fairly easily, such as `numprocs` in supervisord to specify how many processes to run.

Is something similar available with S6?

**Comment by skarnet** [comment]
You can, but it's a bit more complex since one service directory can only supervise one instance. So, if you know in advance the number of copies you need, you can create as many services as that number, and s6 will manage all your instances as if they were separate services (even if the run script is the same or similar).

Alternatively, if you don't know in advance the number of copies you need, s6 now supports [dynamic instances](https://skarnet.org/software/s6/instances.html).

**Comment by intel352** [comment]
@skarnet we're looking at ~100-200 processes per server, so while I could define the value in advance, creating that many service entries doesn't seem tenable.

Can you point me to an example or documentation for the dynamic instance functionality?

Thank you!

**Comment by skarnet** [comment]
Oh, it will work - though of course if you're using glibc then glibc will use *a lot* of memory dynamically linking all the processes - but it will be the same with dynamic instances when you're at full charge, so...

There are no examples for instance usage yet, because it's a very new feature, and no setup in `examples/` because instances are created dynamically in the supervision tree, not static services. I will add a simple roadmap of commands to execute to the documentation.

Are you using the new service model in s6-overlay?

**Comment by intel352** [comment]
Yes, using the new service model

**Comment by skarnet** [comment]
"A lot" has been quantified in [this thread](https://skarnet.org/lists/supervision/2795.html) on the [supervision mailing-list](https://skarnet.org/lists/#supervision); in particular, see [my breakdown](https://skarnet.org/lists/supervision/2804.html) of the RAM used by a single `s6-supervise` process when dynamically linked against glibc, dynamically linked against musl, or statically linked against musl.

If you're using s6-overlay, then you don't have to worry about it: the s6-overlay binaries are all statically linked against musl, so they should take the minimum possible amount of RAM. (About 3 MB for 120 processes.) So I would still recommend going the static instances route.

But if you insist on doing dynamic instances, the steps should be something like:

- Create a templated service directory in `$template`
- Decide how your service will be named: `$service`
- `s6-instance-maker -r $service -- $template /var/tmp/foobar`
- `mv /var/tmp/foobar/$service /etc/s6-overlay/s6-rc.d/`
- Treat `/etc/s6-overlay/s6-rc.d/$service` as you would do any other service: add a `dependencies.d/base` file to it, add a `$service` file to /etc/s6-overlay/s6-rc.d/user/contents.d`, etc.
- At boot time, the service will be started by s6-rc, but no instances will be running
- Dynamically create instances: `for i in $(seq 200) ; do s6-instance-create /run/service/$service instance$i ; done` (this will also start the instances as soon as they're created)
- If you want your instances to be automatically created then you'll have to add a oneshot, depending on `$service`, that performs the `s6-instance-create` loop
- ... and that will have no benefit over doing static instances. Instead of doing all that, you could just have 200 copies of `$template` in `/etc/s6-overlay/s6-rc.d` - all named differently, of course, all depending on `base`, all declared in `user`, and it would give you the exact same result, but with a faster boot time. 😅

**Comment by rfsch** [comment]
Very nice explanation. It's though not clear how to do this. 

Could you please just show a concrete example ? What would $template and $service be ? Are these to be replaced ? 

Thanks

**Comment by skarnet** [comment]
Did you successfully make the setup work one way or another? Can I close this?

**Comment by intel352** [comment]
@skarnet Thanks for the help here, other priorities came up, we haven't tried this configuration approach yet. I'll close this for now and if we have any issues with the instructions you provided, I'll post back.

Cheers

**Comment by intel352** [comment]
@skarnet with static instances, is there a way to associate all the instances, so I can get service status of all instances by checking one name?

**Comment by endersonmaia** [comment]
@skarnet I'm using the `s6-instance-create` strategy but I have no idea how to pass different parameters to each new instance.

I have an `env/` directory at my template, but I'd like to change it for each new instance, is that possible? Or is it even the way to go?

Sorry for hijacking this thread, I can open a new one if you think is better.

**Comment by skarnet** [comment]
The name of the instance you create via `s6-instance-create` is passed as the first argument to the `run` script in every instance.

`env` is copied in every instance, so that's not a place you can instantiate, but you could create a repository of directories anywhere, say `/etc/envdirs`, and store your envdirs there: `/etc/envdirs/foo`, `/etc/envdirs/bar`, etc. And then, in your template run script, you would just call `s6-envdir /etc/envdirs/$1`, and it would import your instance-specific environment.
