### ISSUE TITLE
Dynamic service definition and startup parameters from yaml

### ISSUE THREAD

**Issue by rfsch** [just-containers/s6-overlay#510]
I would like to dynamically start n services of the same executable.
The number of services to dynamically start is in a yaml file provided. From the yaml file a parameter has to be parsed and provided to the service invocation.

I have a python script parsing the yaml. It returns an array of service start up parameters. It also prints export PARAMETER_SRRVICE_N="some parameter service n" for each service definition.
Using eval it would export them to the shell the service is started from allowing it to read the parameter value from the shell environment.

I would like to parse the yaml before invocation of the service in order to pass it's start up parameter. 

I tried to use eval `parse.py` but I am getting the error

exec: fatal: unable to exec eval: No such file or directory

Can you please tell me why exec eval fails ? 
Or suggest/recommend the best approach to take ?

Thank you

**Comment by skarnet** [comment]
You are likely directly writing your shell script in an `up` file. Don't do this: `up` files are not shell scripts. If you want to use a shell, write your script in a file of your chosen location, make it executable, and have the `up` script call that file.

**Comment by rfsch** [comment]
I would actually like to do this in run before starting the service 
What would be the best way to read a parameter from a yaml and pass it to the service as a parameter?
eval did not work 
Now I have tried writing the parameter the an env file and then executing the service
But first I would need to run the parser writing to the env file

My script looks like this 

#!/command/execlineb -P

python parser.py (writes to "env_file")
envfile -i  "env_file" prog 0$param

Unfortunately envfile does get the key value from env_file

I can see env_file written though 

Should this work ? 
Is there a simpler way ? 

Thank you

**Comment by skarnet** [comment]
You know that you can write your run scripts in shell, right?

But if you want to use execline, a run script that would work for you is:
```
#!/command/execlineb -P
if { python parser.py }
envfile env_file
prog params...
```

**Comment by rfsch** [comment]
Thank you so much! Now the only issue I have is that I can't get the parameter from the env_file

The file content is
param=value
I am referencing it with $param 

I tried all combinations ...

Sorry for the many questions.

Thanks

Thanks

**Comment by skarnet** [comment]
The variable are in your environment. If you want to use them in the command line, use the [importas](https://skarnet.org/execline/importas.html) command:
```
#!/command/execlineb -P
if { python parser.py }
envfile env_file
importas param param
prog $param
```

**Comment by rfsch** [comment]
Thank you so much!!! It works now

**Comment by skarnet** [comment]
So now we're reaching the crux of your question. And the short answer is: no, unfortunately, you can't proceed this way, because one service directory can only manage one process. If you want to start several services, you need to find another way.

If you change your yaml file during the lifetime of a container, there's only one way to do it: dynamic instances, a [new feature](https://skarnet.org/software/s6/instances.html) in s6. I'll let you read the documentation first and come back if you have questions. Honestly, I don't recommend doing this - instances work, but changing your service configuration that dynamically goes against the concepts and guarantees of supervision and instead of helping you, s6 will be in the way.

If, however, you only change your yaml file between two container starts, and once you have a container running the number of services stays the same until the container exits, then it's easier, and s6-overlay provides you with an additional way: the `S6_STAGE2_HOOK` variable.

- Write a shell script that parses your yaml file, and from the data it gathers, creates the services you need in `/etc/s6-overlay/s6-rc.d with the correct dependencies to `base` and the correct mentions in the `user` contents - as if you were adding s6-rc services by hand, but in your script.
- In your Dockerfile, define the `S6_STAGE2_HOOK` environment variable, containing the full path to your shell script.
- Your script will be run very early, and s6-rc will run on the database that will have been modified by it, so you will get exactly the services you have created according to your yaml file.

Good luck,

**Comment by rfsch** [comment]
Thank you for your answer. I am looking at dynamic services just now.

There is a misunderstanding. 

I have one service directory per process. In it the yaml is parsed if for the process a definition exists.

**Comment by rfsch** [comment]
.

**Comment by skarnet** [comment]
Okay, now I understand your setup.

So, yes, there is a way to do it like you say, but it's not idiomatic. It's also inefficient because you're restarting services that could just remain up.

In order to do what you want, you need to test whether the current service is active as told by your yaml file, and if it is not, it needs to stop itself. It works, it can be done, but it is considered bad form (because the wanted state of a service should only change by administrator intervention, not by an action of the service itself). To stop itself, the service must invoke the following command: `s6-svc -d .`

So your run script would look like something like:
```
#!/command/execlineb -S1
if { python parser.py }
envfile env_file
importas SERVICELIST SERVICELIST
ifelse -n
 { pipeline { importas SERVICELIST SERVICELIST echo $SERVICELIST } grep -qF $1 }
 { s6-svc -d . }
prog $param
```
This assumes that the list of active services can be found in `env_file` in a variable called `SERVICELIST`, and that the service directory is named after the service. The `ifelse` construct, with the two following blocks, is the execline equivalent of this shell excerpt:
```
if ! echo $SERVICELIST | grep -qF "$1" ; then exec s6-svc-d . ; fi
```
which stops the service if `$1`, i.e. the name of the current service, cannot be found in the list provided by `$SERVICELIST`.

 So, it can be done. But, again, it's not idiomatic, and there's a better way to accomplish what you want:

- Create all your services as s6-rc longruns, defined in `/etc/s6-overlay/s6-rc.d`. But **do not** declare them in the `user` bundle. This will add their definitions to the service database but will not start them at boot time.
- Every time your server gets a request to change your yaml file and update the list of running services, change your yaml file indeed, but ensure there is a way to get the list of active services; let's say you put that list in the `SERVICELIST` variable, like above. Then run the following command: `s6-rc -p change top $SERVICELIST`.
- This command will make it so that the s6-rc services that are brought up are *exactly* the ones defined by `top`, which is the starting environment, plus the contents of the `SERVICELIST` variable. It will stop the services that should not be up anymore and start the ones that have just been activated.
- This is the most idiomatic way to do what you want. It's also the most efficient, because for every state change, you only have to process your yaml file *once*, instead of once per service.

**Comment by skarnet** [comment]
Did you manage to get your setup working? Can I close this?

**Comment by rfsch** [comment]
Thank you so much for your response. This is working very well. I have another problem though i need to solve optimally.

Each of the services need a startup name defined in the config file. The name is passed as a parameter on service startup. I would like to write both the services active and their startup names before the startup of the services themselves. Can this be achieved using a dependent service run once before at every container invocation?

**Comment by skarnet** [comment]
Sure. Create a oneshot that does whatever you need to do (print the active service list and their names), and have every one of your longruns depend on it. That oneshot will be run before your longruns.

**Comment by rfsch** [comment]
Very well. Thank you.

**Comment by skarnet** [comment]
Yes, have the oneshot write a file. The oneshot will only run once, as the name suggests. And yes, no services that depend on it will run if the oneshot fails; you should want that, since your services won't be able to get their parameters if the oneshot fails - but if you don't, then wrap your oneshot script so it always exits 0, and s6-rc will see it as always successful.

 A monitor can run as a longrun that depends on the service(s) it's monitoring. If your only monitoring tool is a health checker, then make sure your service has readiness notification enabled, then the run script for the monitor can be something like this:
```sh
#!/bin/sh -e
if $healthcheck_command; then
  exec sleep $period
else
  $write_an_alert
  s6-svc -rwR /run/service/$your_service
fi
```
With proper dependencies and readiness notification, the monitor will only run when `$your_service` is ready, so it doesn't fail at start. On healthcheck success, the monitor will sleep for `$period` seconds, then die and be restarted by the supervisor (which prevents you from having to write your own loop), so you should adjust `$period` depending on how often you want to perform a check. On failure, an alert will be written, `$your_service` will be restarted, and the monitor will wait until the service has properly restarted and is ready again, then the polling will resume.
 
Note that it's impossible to provide generic health monitoring tools, so s6 doesn't; it can only help you run the monitoring tools that your software should provide.

**Comment by rfsch** [comment]
Thank you. I have set up a dependency of each service to a oneshot writing the services file. Unfortunately it is run once. How can I make it run before dynamically starting the services whenever there is a change in the number of services?

**Comment by skarnet** [comment]
It wasn't clear it wasn't what you wanted.

s6-rc is not well-suited to handle dynamism. If you have dynamic scripts, they should be run wherever the dynamism happens. In your case, you certainly have a hook somewhere that triggers when there is a change in your service configuration; so, put your script in that hook.

**Comment by rfsch** [comment]
Understood.. oneshot really means it's name.. thanks.

**Comment by skarnet** [comment]
Can I close this issue?
