### ISSUE TITLE
Question: how to define a s6-rc.d service as mandatory?

### ISSUE THREAD

**Issue by felipecrs** [just-containers/s6-overlay#513]
Mandatory means:

- For oneshots: I want the container to exit if the oneshot service fails.
- For longruns: I want the container to exit if the longrun fails or exits, instead of restarting the service.

I looked on the https://skarnet.org/software/s6-rc/s6-rc-compile.html but I could not find what I was looking for.

I'd appreciate any help.

**Comment by skarnet** [comment]
If you want the container to exit if *any* service fails, define `S6_BEHAVIOUR_IF_STAGE2_FAILS` to 2.

If you have *one* mandatory service, run it as your CMD: the container will die when this process dies.

If you have a mix of several mandatory services along with some non-mandatory ones, however, it's a bit more complicated. With s6-rc, you can't define a service as mandatory, because s6-rc doesn't know that it's running in a container, it doesn't know what "mandatory" would mean. When one service fails, s6-rc keeps going until it cannot transition any service anymore, then it exits with a code saying some transitions failed.

What you *can* do is test what services are active after s6-rc has completed, and trigger a container exit if the services you want aren't all active. You would do that in a CMD, which is run after s6-rc completes. So, replacing `$mandatory` with your list of mandatory services, your CMD could be a script that looks like:
```sh
#!/bin/sh -e
list=`s6-rc -a list`  # lists active services, one per line
for service in $mandatory ; do
  if ! echo "$list" | grep -qFx "$service" ; then
    echo 1 > /run/s6-linux-init-container-results/exitcode  # to say the container failed
    exec /run/s6/basedir/bin/halt
  fi
done
exec s6-pause  # or exec into your real CMD if you have one
```

Hope this helps.

**Comment by felipecrs** [comment]
Oh, this is interesting! I will give it a try. Thank you!

**Comment by felipecrs** [comment]
Question, is there a way to run a script in case one oneshot service fails? Apparently, `down` is not executed in such situation.

It would be really helpful to be able to have a `finish` (like the longrun ones) for oneshots, so I could simply call something like:

```bash
#!/bin/bash

set -e

if [[ "${1}" -ne 0 ]]; then
  echo "${1}" > /run/s6-linux-init-container-results/exitcode
  exec /run/s6/basedir/bin/halt
fi
```

**Comment by skarnet** [comment]
No, because in the design of s6-rc there's always a way to run a command after s6-rc exits, whether it fails or succeeds, and check which services have successfully completed their transition and which ones have not.

In s6-overlay, this is used by `S6_BEHAVIOUR_IF_STAGE2_FAILS`, which is less control than s6-rc allows you, but we had to simplify somewhat.

If you want to execute something when a given oneshot fails, you can always do it in the oneshot script itself:
```sh
#!/bin/sh
(your oneshot)
e=$?
if test $e -gt 0 ; then
  (your failure script)
fi
exit $e
```

**Comment by felipecrs** [comment]
I think this is a decent idea. I can work with some `trap`s to ensure my commands are called before the oneshot exits.

It would be nice if s6-rc had a simpler solution for this problem, but given what we have today this is as far as we can go, I think.

Again, thanks a lot.
