### ISSUE TITLE
Is there a way to delay starting a service until after another oneshot service is finished?

### ISSUE THREAD

**Issue by jerrac** [just-containers/s6-overlay#514]
I have 3 services. 2 oneshots and one longrun. I'd like to make oneshot-b only start after oneshot-a has finished. And longrun only start after oneshot-b has finished.

Is that possible?

The specific issue I am trying to solve is not starting until I've detected the remote database and message broker are actually up. Then I want to run a quick setup script that initializes a few things in my app. Finally I want to start the actual app. (apache in this case.)

Is there a clean way to do this via S6? Or do I need to just wrap apache in a script that runs the oneshots before starting apache?

So far I've tried setting oneshot-a as a dependency of oneshot-b, and oneshot-b as a dependency of longrun. But they all start up at once. Which makes sense if you are trying to have dependencies that need to be running, but not finished, before starting the next service.

Thanks in advance!

**Comment by skarnet** [comment]
If `oneshot-b` has a dependency on `oneshot-a`, then it definitely should only start when `oneshot-a` has finished, that's the whole point of dependencies. Make sure `oneshot-a` does not background itself: the transition will be considered a success as soon as the *main process* exits 0.

Same thing with `longrun` having a dependency on `oneshot-b`. If `oneshot-b` does not background itself, then `longrun` will only start once the main process of `oneshot-b` exits 0.

If your dependencies have been set up correctly, you should see it in your logs: the line
```
s6-rc: info: service oneshot-a successfully started
```
should always appear *before* the line
```
s6-rc: info: service oneshot-b: starting
```
and then the line
```
s6-rc: info: service oneshot-b successfully started
```
should always appear *before* the line
```
s6-rc: info: service longrun: starting
```
If it's not the case, then something's wrong in the way you've written the dependencies.

It's a little more complicated when you want to make a service depend on a longrun (because you need a way to tell that the longrun is ready, so you have to plug your daemon's way of notifying readiness into the s6 framework for it), but here, you're only depending on oneshots, so it's as straightforward as it gets.

**Comment by jerrac** [comment]
I tried again and ran into the error that [this](https://github.com/just-containers/s6-overlay/issues/433#issuecomment-1086980677) comment resolved. After adding that environment variable, everything is working as expected. Apache isn't started until my rabbitmq and db instances are actually up.

Which makes me wonder what the heck I was doing earlier that wasn't working. :\ I had mostly switched over to my idea of just wrapping everything in a single script, so when I switched back to not doing that, I must have missed something. And of course I hadn't committed my changes to git... 

Thanks for the pointers! And quick response. :)

**Comment by skarnet** [comment]
Note that for future incremental improvements, if your rabbitmq and  db are running in the same container, you could examine their starting scripts and try to make them longruns instead, so the processes would be supervised by s6 as well. 😉
