### ISSUE TITLE
What happens in kill when use sudo to run init?

### ISSUE THREAD

**Issue by HowardMei** [just-containers/s6-overlay#52]
I created a sudo user devops and use it as the default user.
I observed a difference in container behaviour of finishing a non daemon cmd like: 
docker run --rm -it s6base ls /etc/s6  

**Dockerfile:**
USER            root
ENTRYPOINT      ["/init"]
**stdout:**
$ [s6-finish] syncing disks.
$ [s6-finish] sending all processes the TERM signal.
$ [s6-finish] sending all processes the KILL signal and exiting.  

**Dockerfile:**
USER            devops
ENTRYPOINT      ["sudo","/init"]
**stdout:**
$ [s6-finish] syncing disks.
$ [s6-finish] sending all processes the TERM signal.
$ Hangup  

I checked the scripts in /etc/s6 to search for the clue but didn't get it.
if 'Hangup' means '-HUP/-15', it is a grace way to TERM the container.
But not sending the KILL signal concerns me.

**Comment by glerchundi** [comment]
Hi @HowardMei,

Probably because stage3 is not being run as pid 1, s6-nuke is killing it [`here`](https://github.com/just-containers/s6-overlay/blob/master/builder/overlay-rootfs/etc/s6/init/init-stage3#L43). Could I ask why are you wrapping the `/init` script with sudo? If you want to drop privileges maybe with [`s6-setuidgid`](http://skarnet.org/software/s6/s6-setuidgid.html) would be enough.

I think this is somehow related to #19. I would like to know what use cases make direct use of `/init` as the ENTRYPOINT impossible.

**Comment by HowardMei** [comment]
Thank you @glerchundi for pointing out #19 but I don't like the workaround of chown of s6 conf dir.  
I realized what I really want is running daemon as user `devops:sudo` which means the priviledge changing should happen in init-stage2 rather than in container init stages.  
Is it possible to pass a `-u devops:sudo` option via `/init` script to let `s6-setuidgid` use it during starting the supervision of long-lived processes?  
Or even better, users could specify `devops:sudo` in the /etc/services.d/* scripts.  
I'll try the second way with /init running as root :-)

**Comment by glerchundi** [comment]
> Or even better, users could specify devops:sudo in the /etc/services.d/* scripts.

I think it's the way to go, we're already doing that:
in `s6-overlay`: https://github.com/just-containers/s6-overlay/blob/master/builder/overlay-rootfs/etc/s6/services/s6-svscan-log/run#L3-L4
in `nginx-loadbalancer`: 
https://github.com/just-containers/nginx-loadbalancer/blob/master/rootfs/etc/services.d/nginx-error-log/run#L3-L4

In these cases we permit fallbacking to predefined uid/gid in case that account didn't exist. But in your case with `s6-setuidgid`would be enough (internally it uses `envuidgid` & `applyuidgid`).

**Comment by pikeas** [comment]
@glerchundi The `nginx-loadbalancer` service you linked to no longer drops to a different user. Could you add an example to the README (probably cribbing from https://github.com/just-containers/s6-overlay/blob/master/builder/overlay-rootfs/usr/bin/logutil-service-main) showing the right way to run a service as a different user?

Also, I've used https://github.com/tianon/gosu in non-s6 containers. Is it fair to say this is no longer necessary when using s6-overlay and user-dropping?

**Comment by glerchundi** [comment]
> @glerchundi The nginx-loadbalancer service you linked to no longer drops to a different user.

It does but it's inside the `logutil-service` utility. Before executing anything it drops privileges to `nobody:nogroup` (or it uses `32768:32768` uid/gid if `nobody` doesn't exist).

> Could you add an example to the README (probably cribbing from https://github.com/just-containers/s6-overlay/blob/master/builder/overlay-rootfs/usr/bin/logutil-service-main) showing the right way to run a service as a different user?

Will do, but I would recommend you to take a look to `s6` documentation, it explains how everything works very clearly: [s6](http://skarnet.org/software/s6/) and [s6-portable-utils](http://skarnet.org/software/s6-portable-utils/).

Probably, and in most cases, you would need no more than `s6-setuidgid` because it sets uid/gid to the target account and executes the following command without doing anything else. In `nginx-loadbalancer` example it uses `s6-envuidgid` + `s6-applyuidgid`, which behaves exactly in the same way as `s6-setuidgid` does except it allows to specify custom uid/gid if the target account doesn't exist:

```
s6-setuidgid daemon
your-cmd
```

Which is a shorthand of:

```
s6-envuidgid daemon
s6-applyuidgid -U
your-cmd
```

> Also, I've used https://github.com/tianon/gosu in non-s6 containers. Is it fair to say this is no longer necessary when using s6-overlay and user-dropping?

Right :-)
