### ISSUE TITLE
Option for non blocking s6-log?

### ISSUE THREAD

**Issue by DoobleD** [just-containers/s6-overlay#533]
Currently s6-log is started with the -b ([blocking](https://skarnet.org/software/s6/s6-log.html)) option. 

https://github.com/just-containers/s6-overlay/blob/9eda003e19a6e01edd951ad84dd50a4804129d73/layout/rootfs-overlay/package/admin/s6-overlay-%40VERSION%40/libexec/logutil-service-main#L11

This can slow down services, which may not be acceptable for services with speed requirements. Could we have an option to choose whether we want to start s6-log with or without the -b argument?

It could be a simple env var like `S6_LOGGING_BLOCK` for instance. I'd be happy to open a PR if that sounds reasonable.

**Comment by skarnet** [comment]
If you're in the rare case that your service is producing abundant logs really fast, and you think the blocking behaviour is slowing down your service, *and* testing/benchmarking proves s6-log to really be the limiting factor, *and* you know that your service, despite producing logs faster than they can be written, will not cause unbounded accumulation of logs in memory (which may cause s6-log to eventually fail, exit, and drop all these yet-unwritten logs) then you have enough practical knowledge to script your way around s6-log yourself instead of relying on `logutil-service`, and can omit the `-b` option in your script.

For the huge majority of people, however, `-b` is the correct and safe behaviour, that won't blow up in anyone's face. Which is what we want from a user-friendly wrapper.

**Comment by DoobleD** [comment]
Thanks for the reply @skarnet. I'm trying to verify that s6-log in blocking mode is indeed the limit factor in my case. I see no much harm in having options for rare cases, but I'll try another approach then. :)
