### ISSUE TITLE
Log File Renaming?

### ISSUE THREAD

**Issue by RozJC** [just-containers/s6-overlay#543]
Hello,

I'm looking for the possibility to save log and their subsequent archive files to different filenames rather than the standard ones that the s6-log feature creates.

Is this possible within s6 or does it need to be done by an external process?

Thanks

**Comment by skarnet** [comment]
You *cannot* rename `current`, the file s6-log is currently writing to. This is the only absolute.

You *should not* rename the files created by s6-log and keep all its features intact, because s6-log relies on the naming pattern to know which files are log archives and take them into account when performing a log rotation. However, if you have no use for the archiving control mechanism of s6-log, you can take `@*.s` archive files and move them somewhere else; or you could even use the `n0` directive in your s6-log script along with a `!` directive to process log files as you see fit. For instance:

```
s6-log n0 t !"exec cat > archive-`date`" /var/log/foobar
```
will still create archive files under `/var/log/foobar`, but with a different name.

Be aware that if you do this, s6-log will be unable to check for disk exhaustion or similar limits, and you're depriving yourself of much of its benefits.

**Comment by RozJC** [comment]
Thanks for the reply.

I don't mind having the archiving functionality.

It's more that in my current setup, I am unable to process the TAI64n filename structure of the archived files, so I was looking for a way to be able to move or rename the files to use a date that is more user-friendly.

**Comment by skarnet** [comment]
Unfortunately, user-friendly dates are difficult to parse, and the advantage of TAI64N is that it allows s6-log to see at a glance what is an archive file and what is not, without adding extra complexity.

If it is an option for you, note that the `s6-tai64nlocal` tool converts a TAI64N stamp to an RFC 3339 date. So you could use something like `ls -1 @*.s | s6-tai64nlocal | sed 's/\.s$//'` and get a list of dates for the archive files.
