### ISSUE TITLE
s6-notifyoncheck: fatal: s6-supervise not running.

### ISSUE THREAD

**Issue by SSoft7** [just-containers/s6-overlay#549]
overlay version: v3.1.5.0

My service fails to run if I wrap it with s6-notifyoncheck command. If I run it without s6-notifyoncheck command then it just runs fine but with it gives the following error

> s6-notifyoncheck: fatal: s6-supervise not running.

Here is the exact command without s6-notifyoncheck

```
exec \
    s6-setuidgid abc "${APP_BIN_PATH}filebrowser" --config="${APP_CONFIG_FILE}" >> "${LOG_FILE:-"/config/application.stdout.log"}" 2>&1
```

with s6-notifycheck

```
exec \
    s6-notifyoncheck -d -n 300 -w 1000 \
    s6-setuidgid abc "${APP_BIN_PATH}filebrowser" --config="${APP_CONFIG_FILE}" >> "${LOG_FILE:-"/config/application.stdout.log"}" 2>&1
```

> data/check file exists in this case and is executable

Can anyone please provide me with some direction to debug this? I don't have much knowledge about s6 internals so I need some guidance/direction to find out the root cause.

**Comment by skarnet** [comment]
Is something in your script changing the current working directory before executing the line? s6-notifyoncheck will print that message if it's not in the service directory (because it checks that the supervisor is alive via a relative path).

If it's the case, you can solve this by changing the working directory *in* the final line: `s6-setuidgid abc cd $new_wd ${APP_BIN_PATH}filebrowser ...`

Yes, it will work: `cd` here is `/command/cd`, an execline program that will change the working directory then execute the rest of the command line.

**Comment by SSoft7** [comment]
> Is something in your script changing the current working directory before executing the line? s6-notifyoncheck will print that message if it's not in the service directory (because it checks that the supervisor is alive via a relative path).
> 
> If it's the case, you can solve this by changing the working directory _in_ the final line: `s6-setuidgid abc cd $new_wd ${APP_BIN_PATH}filebrowser ...`
> 
> Yes, it will work: `cd` here is `/command/cd`, an execline program that will change the working directory then execute the rest of the command line.

Yes, I have a line just before this, which is unnecessary at this moment but at least now I know what is wrong
`cd "$APP_BIN_PATH" || exit`
Is this matter mentioned somewhere in the docs? If yes, please provide a link so that I can get a fair idea of where to look if I get stuck on similar issues.
If not, then I think it should be added.

I also have seen commands like `s6-setuidgid abc cd` on other s6-based images but did not know that it is an execline program, not the regular cd command.

Thank you for all the info.

**Comment by skarnet** [comment]
- I will add a note in the s6-notifyoncheck documentation to explicitly say that s6-notifyoncheck should be used in the service directory.
- `cd` as a shell builtin cannot be used in a command line, because you cannot exec into a shell builtin. That is one of the reasons why execline has a `cd` command: so you can change directories as part of a command line.
