### ISSUE TITLE
Release builds in .tar format?

### ISSUE THREAD

**Issue by Kamillaova** [just-containers/s6-overlay#569]
AFAIK with .tar releases it will be possible to do something like this:
```Dockerfile
FROM debian
ADD https://github.com/just-containers/s6-overlay/releases/download/v3.1.6.2/s6-overlay-x86_64.tar /
```

Reference:
https://www.reddit.com/r/docker/comments/8y2zyx/how_to_add_a_empty_directory_to_a_scratch_image/

**Comment by nekopsykose** [comment]
ADD works with .tar.xz, see https://docs.docker.com/reference/dockerfile/#add , specifically 'recognized compression format'

**Comment by skarnet** [comment]
If only all issues could be solved that easily 😁

**Comment by nekopsykose** [comment]
it's not solved since i misread the docs, add indeed doesn't work with .tar.xz links.  

there is a.. pretty ok workaround, in https://github.com/moby/moby/issues/2369#issuecomment-457219856 , which i would personally use since i don't mind those kinds of workarounds, but it's not exactly the same kind of thing.

**Comment by skarnet** [comment]
Hmm. Personally I'm ok with one ADD line followed by one RUN line, but if Docker is adding a special case for `.tar` and `.tar.gz`, then I'm of the opinion they should also specialcase `.tar.bz2` and `.tar.xz`, at least.
