### ISSUE TITLE
Allow to set `S6_CMD_WAIT_FOR_SERVICES_MAXTIME` per longrun service

### ISSUE THREAD

**Issue by felipecrs** [just-containers/s6-overlay#570]
Taking as example the shutdown sequence, s6-overlay by default waits forever for s6-rc services to finish. There, each service can be tweaked with a variety of options like `timeout-kill` (usually the most useful), `timeout-finish`, and even `timeout-down` seems to apply (_and I'm not sure if that's expected for a longrun service_).

However, during the initialization with `S6_CMD_WAIT_FOR_SERVICES=1`, you can only set a global timeout through the `S6_CMD_WAIT_FOR_SERVICES_MAXTIME`. I believe it would also be nice to allow each service to provide their expected startup time.

This would be useful for cases where the base image ships with some pre-defined services, but users want to extend with their own services that can potentially take more time, without having to override the global `S6_CMD_WAIT_FOR_SERVICES_MAXTIME`.

I admit however it isn't big deal to re-define `S6_CMD_WAIT_FOR_SERVICES_MAXTIME` anyway, but I just wanted to open this issue to hear your opinion about it.

**Comment by skarnet** [comment]
s6-rc services do have an individual timeout: a number of milliseconds you can write in the `timeout-up` file. So you can disable the global timeout and use `timeout-up` files (and `timeout-down` exists as well, but it's not as useful).

And honestly, I agree with you here. Initially I set the default global timeout to a finite value because I thought it would help people with failing services, hanged network connections, and so on; but the reality, as proven by the number of issues that have been opened because of it, is that a finite default global timeout trips people up much more than it helps them. Even if it's documented, it's not something people *expect*.

So yeah, I plan to disable the timeout by default in a future release of s6-overlay. It's a behavioral change, so it requires a major version update; I'm just waiting for another good reason to perform a major version update, something that requires a breaking change anyway, and I'll bundle `S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0` with it.

**Comment by felipecrs** [comment]
`timeout-up` + `S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0` [works fine](https://github.com/felipecrs/jenkins-agent-dind/pull/115), thank you!

> So yeah, I plan to disable the timeout by default in a future release of s6-overlay. It's a behavioral change, so it requires a major version update

Right, I think it makes sense. I would probably even go as far as removing most of hardcoded default timeouts for consistency, another example being `timeout-finish` which [currently is 5000ms](https://skarnet.org/software/s6/servicedir.html#:~:text=a%20SIGKILL.%20The-,default%20is%205000,-%3A%20finish%20scripts%20are). Except perhaps for `S6_SERVICES_READYTIME`.

Anyway, feel free to close this issue at your preference.
