### ISSUE TITLE
Avoid SIGTERM to main process when stopping

### ISSUE THREAD

**Issue by fernandolcx** [just-containers/s6-overlay#585]
My app have two scripts: 

- `run.sh` which starts my app and it keeps running until `shutdown.sh` invocation;
- `shutdown.sh` which performs a clean termination of all process started by `run.sh`, and only it can assure a clean and safe termination;

When I do `docker stop`, my app begins the termination via `shutdown.sh` but after few seconds it crashes because `run.sh` has been killed with all their child process.

How can I tell s6-overlay to ONLY run `shutdown.sh` and avoid SIGTERM to be sent to `run.sh` (`CMD`) and wait?

Dockerfile:

```dockerfile
CMD ["/opt/myapp/bin/run.sh"]

RUN ln -s /opt/myapp/bin/run.sh /etc/s6-overlay/s6-rc.d/myapp/run
RUN ln -s /opt/myapp/bin/shutdown.sh /etc/s6-overlay/s6-rc.d/myapp/finish
RUN echo 'longrun' > /etc/s6-overlay/s6-rc.d/myapp/type

ENTRYPOINT ["/init"]
```

Is there any approach to solve this?

**Comment by skarnet** [comment]
There are two things here.

The first thing is that you seem to be running your application twice: both as a service (`/etc/s6-overlay/s6-rc.d/myapp`) and as a CMD. This will not work. I assume you're currently making it work because you're not declaring `myapp` in the `user` bundle, so s6-rc does not start it when bringing services up, and `run.sh` is only run when s6-overlay gets to running your CMD. But `myapp` still makes it into the service database; if you don't intend to run it as a service, you should not put it under `/etc/s6-overlay-s6-rc.d`.

The second thing is having a specific termination command. This is generally bad software design. Long-lived processes are generally stopped by reacting to a signal; it's the only way to ensure they interact properly with several service management systems and general Unix behaviour where signals are sent to entire process groups to terminate them. If it's currently not the case for `myapp`, it might be something worth investigating and changing, if possible.

s6-overlay does not support specific shutdown commands, it only supports termination signals. If you run `myapp` as your CMD, you will not be able to avoid a SIGTERM being sent to it when you run `docker stop`, sorry.

That said, there is still a way to do what you want: instead of running `myapp` as a CMD, keep it as a service brought up by s6-rc. Make `myapp` depend on `base` and add it to the `user` bundle. Do not use a CMD line. Then tell s6 not to send any termination signal to the service:

`echo 0 > /etc/s6-overlay/s6-rc.d/myapp/down-signal`

You will also need to prevent s6 from restarting the service when it is terminated by your external `shutdown.sh` command. For that, right *before* executing `shutdown.sh`, run the following:

`s6-svc -O /run/service/myapp`

(So, add the previous line to the place where you tell `docker stop` to run `shutdown.sh`, right before the `shutdown.sh` invocation.)

Hope this helps.

**Comment by fernandolcx** [comment]
I've just created a service instead of using CMD and it looks it worked just fine:

`/etc/s6-overlay/s6-rc.d/myapp/run`:

```bash
#!/command/execlineb -P
with-contenv
execline-cd /opt/myapp/bin/ /opt/myapp/bin/run.sh
```


`/etc/s6-overlay/s6-rc.d/myapp/finish`:
```bash
#!/command/execlineb -P
with-contenv
execline-cd /opt/myapp/bin/ /opt/myapp/bin/shutdown.sh
```

Dockerfile:

```Dockerfile
# CMD ["/opt/myapp/bin/run.sh"]

COPY ./run /etc/s6-overlay/s6-rc.d/myapp/run
COPY ./finish /etc/s6-overlay/s6-rc.d/myapp/finish

RUN echo 'longrun' > /etc/s6-overlay/s6-rc.d/myapp/type
RUN touch /etc/s6-overlay/s6-rc.d/user/contents.d/myapp

ENTRYPOINT ["/init"]
```

Thanks for the help!

**Comment by skarnet** [comment]
Note that it's probably not doing what you intend it to. A `./finish` script is only executed once the `./run` script is already dead. So your `run.sh` is first killed by a signal, then `./finish` runs and executes your `shutdown.sh`, which probably does nothing since `run.sh` is dead at this point.

You need the `s6-svc -O /run/service/myapp` and `down-signal` dance if you really want your application to be killed when you run `shutdown.sh`.
