### ISSUE TITLE
init-stage2: order of initialization tasks

### ISSUE THREAD

**Issue by itheiss** [just-containers/s6-overlay#68]
Hi,

first of all thanks for this great project. It solved so many problems with my homebrew solution.

Here is my question:

I often need to create directories (e.g. /run/xxx) for my docker containers which I implement as a initialization script inside cont-init.d. As the scripts for applying owners & permissions inside fix-attrs.d run before the cont-init.d scripts I have to deal "manually" with the permissions inside the cont-init.d scripts.

Are the any reasons why the fix-attrs.d scripts run before the cont-init.d scripts? I think the cont-init.d scripts could benefit from the fix-attrs.d scripts if we could swap the order.

Thanks and regards

Ingo

**Comment by robinroestenburg** [comment]
I also had this problem, but I have since moved to the following strategy:

* add the directories to the rootfs that is added in the Dockerfile
* set permissions of directories in `fix-attrs.d` script

Also, moving the `fix-attrs` stage after the `cont-init` stage causes similar problems. For example, some of my `cont-init` scripts need the permissions to be set up correctly in order for them to work correctly.

**Comment by itheiss** [comment]
Thanks for your reply. Adding the directories to the rootfs is a good hint. Thanks!

**Comment by glerchundi** [comment]
haha, great to see people following best practices ;-)

@itheiss take a look how does [`nginx-loadbalancer`](https://github.com/just-containers/nginx-loadbalancer) resolve this issue, as pointed by @robinroestenburg, creating them inside rootfs. Don't forget to add a `.gitignore` to the folder so that git commits properly.
