### ISSUE TITLE
Stopping the container when a service fails.

### ISSUE THREAD

**Issue by sameersbn** [just-containers/s6-overlay#87]
My docker container relies on env parameters to configure certain aspects of the main daemon process, which is configured as a service.

If the user does not configure these parameters properly, ideally I want the container to error out, which means that the service/run script exits with an error the container should stop. But with s6-overlay, the service will be relaunched over and over leaving it unusable. Is it possible to return with an error code that will make the container error out and stop?

**Comment by sameersbn** [comment]
I was going through the README again to see if I could find some hints regarding this issue. I think s6-overlay expects me to run the main daemon ("the thing") as a command rather than a service so that went it fails, it will take the whole container down with itself.

Please correct me if i am wrong.

**Comment by smebberson** [comment]
@sameersbn, I'm not from the s6-overlay team but I use it quite extensively. I use this script to bring down a container, when a service crashes:

```
#!/usr/bin/execlineb -S0
if -n { s6-test $# -ne 0 }
if -n { s6-test ${1} -eq 256 }

s6-svscanctl -t /var/run/s6/services
```

This should be setup as a `finish` script within your service directory. There might be a better way... hopefully someone from the s6-overlay can chime in here.

**Comment by sameersbn** [comment]
@smebberson thanks.. does this script make the service take down the container at all time or only when the service/run script returns a specific error code?

**Comment by smebberson** [comment]
@sameersbn, the answer to that lies in here http://skarnet.org/software/s6/s6-supervise.html. s6-overlay hangs together by s6 itself. Read it all, but in particular, dot-point 7. That should explain :)

**Comment by glerchundi** [comment]
If you want to take the supervision tree down because your main daemon failed, @smebberson's solution should work. Take a look to [this comment](https://github.com/just-containers/s6-overlay/issues/41#issuecomment-95461028), the whole thread is interesting too.

But...

If you're trying to validate if the user indeed has provided the required envvars, I'd pick a sanity check init script:
`/etc/cont-init.d/00-sanity-check`:
```
#!/usr/bin/execlineb -P
with-contenv
if { import -i YOURENV1 }
if { import -i YOURENV2 }
if { import -i YOURENV3 }
```

**untested**

If this script fails for whatever reason and you've executed your container with `S6_BEHAVIOUR_IF_STAGE2_FAILS=2`, it'll exit as soon as any validation fails.

Does this work for you?

**Comment by sameersbn** [comment]
@glerchundi @smebberson I think it should work. I will perform some tests and see what works best for me. Right now I am in a POC phase, as a result I am evaluating all possible options to see what works best.

**Comment by glerchundi** [comment]
Great. If your default behaviour is to fail if one of your init scripts failed {cont-init.d,fix-attrs.d} (as it's for most of us), you can add `S6_BEHAVIOUR_IF_STAGE2_FAILS` env in your `Dockerfile` in order to avoid typing it in each container execution.

Please close this issue if you feel that this solved it.

**Comment by sameersbn** [comment]
thanks again.

**Comment by hjwp** [comment]
> @sameersbn, I'm not from the s6-overlay team but I use it quite extensively. I use this script to bring down a container, when a service crashes:
> 
> ```
> #!/usr/bin/execlineb -S0
> if -n { s6-test $# -ne 0 }
> if -n { s6-test ${1} -eq 256 }
> 
> s6-svscanctl -t /var/run/s6/services
> ```
> 
> This should be setup as a `finish` script within your service directory. There might be a better way... hopefully someone from the s6-overlay can chime in here.

this is great but is there a way to make the container exit with a non-zero exit code?

**Comment by jprjr** [comment]
I think you could write a file with the exit code to `/var/run/s6/env-stage3/S6_STAGE2_EXITED`

You'll want to do that in a `cont-finish.d` script though, I believe it would be overwritten if you write it any earlier.

I could look into a method for specifying the container exit code specifically.

**Comment by hjwp** [comment]
I'll try that!

another question:  in dev, rather than prod, it's useful to be able to override this sort of "fail hard on exit" behaviour, and instead be able to request a soft restart.  can you think of any way of doing that, once a `finish` script has been set up?  `s6-svc -h` and `s6-svscanctl -i` both seem to cause the container to shutdown, which i guess is expected if you have a finish script... is there any way to ask the supervisor to bypass the finish script and just restart the services?

**Comment by hjwp** [comment]
just reading the docs. maybe i can customize my `finish` script to act differently for different signals?  apologies for the stream-of-thought.

**Comment by hjwp** [comment]
So I think what I _actually_ want is this?

```
#!/usr/bin/execlineb -S0
# this file says that if our service dies unexpectedly, the whole container should die.
if { s6-test $# -ne 0 }  # if we exited with a nonzero code
if { s6-test ${1} -ne 256 }  # 256 means we were killed by a signal, eg from s6-svc
s6-svscanctl -t /var/run/s6/services  # exit all other services, kill the container
```

**Comment by hasan4791** [comment]
New user to s6 entirely and I was trying to achieve similar results in S6 v3 and having some difficulties. I'm running a wireguard service which fails to run but the container isn't being restarted even though I had handled the exit code in the finish script. What I'm observing here is, the finish script isn't being invoked on service failure.
```
s6-rc: info: service svc-wireguard: starting
Warning: `/config/wg0.conf' is world accessible
Unable to access interface: Operation not permitted
[#] ip link delete dev wg0
Cannot find device "wg0"
s6-rc: warning: unable to start service svc-wireguard: command exited 1
```
Is there any way to properly handle such scenarios?

**Comment by skarnet** [comment]
If you have a service that your container depends on, i.e. the container should restart when the service fails (or exits), then my advice is not to supervise it, but run it as the CMD instead. s6-overlay is designed to exit when the CMD exits.

Sending control commands via a run or finish script is just too error-prone; it can be done (there's a section in the documentation for this) but it's more complex than most setups need to be.

**Comment by hasan4791** [comment]
@skarnet Thank you for your quick look. Since there are multiple services, in CMD we have to write our own script in monitoring all those process. Will dig further on this.

**Comment by skarnet** [comment]
@hasan4791 The point is to run all your auxiliary services supervised, and only the "main" one as CMD. The supervisor will restart auxiliary services on failure (you can add monitoring to that if you so choose, of course); only death of the main process will trigger an exit from the container.

**Comment by felipecrs** [comment]
@skarnet, don't you think this can be made a little simpler for end-users? Right now, most Home Assistant add-ons have some finish script like this:

https://github.com/blakeblackshear/frigate-hass-addons/blob/0b39fea5afba5cd232a5007e86f91b690a552943/frigate_proxy/rootfs/etc/s6-overlay/s6-rc.d/nginx/finish
https://github.com/hassio-addons/addon-vscode/blob/dae2e404f0e4001b1e2ce11f3b6eb8fc23ec5fa7/vscode/rootfs/etc/s6-overlay/s6-rc.d/code-server/finish

Which, to be honest, no one understands, but they just know it works.

And I understand, the main process should be the `CMD`, but there are certain cases where that cannot be accomplished.

For example:

In the Asterisk Home Assistant add-on, the main purpose is to run Asterisk:

https://github.com/TECH7Fox/asterisk-hass-addons/blob/e55c7919aeb9b6301e420a59f88e68c3c8c9ef40/asterisk/rootfs/etc/services.d/asterisk/run

However, there is also one feature which is to allow sending commands to this container through stdin. As you cannot attach the stdin to a regular service, the only alternative is to run Asterisk as a regular service, and then run your stdin handler as `CMD`:

https://github.com/TECH7Fox/asterisk-hass-addons/blob/e55c7919aeb9b6301e420a59f88e68c3c8c9ef40/asterisk/Dockerfile#L292
https://github.com/TECH7Fox/asterisk-hass-addons/blob/e55c7919aeb9b6301e420a59f88e68c3c8c9ef40/asterisk/rootfs/stdin.sh

And I hope you agree this is a good example for when your main process cannot be executed as `CMD`.

---

How about allowing to define the service `type` as `critical-longrun` (name can probably be improved) as opposed to just `longrun`?

When a service's type is `critical-longrun`, s6-overlay will take down the supervision tree if the service fails (rather than just restarting), forwarding its exit code whenever possible.

**Comment by skarnet** [comment]
@felipecrs I don't understand.

> As you cannot attach the stdin to a regular service, the only alternative is to run Asterisk as a regular service, and then run your stdin handler as `CMD`

I mean... no? That sounds like the _perfect_ case to run Asterix as your CMD, it seems to me, especially since

> the main purpose is to run Asterisk

So, I get that you would like a simpler way to stop a container when a supervised service exits, but the examples you're using to illustrate the need are doing the exact opposite: they illustrate the fact that the main service really should run as the CMD.

Do you have better examples?

In any case, I _could_ add a "waitfor" command to s6-overlay, that you would run as `CMD [ "waitfor", "foo" ]` and that would exit when supervised service `foo` exits, which would make the container exit - that may indeed simplify the `./finish` scripts hacks. But that will not help with stdin, so your Asterix thing wouldn't be able to use it.

**Comment by felipecrs** [comment]
First, thanks for answering and even considering!

> I mean... no? That sounds like the perfect case to run Asterix as your CMD, it seems to me, especially since

Did you see the [stdin.sh](https://github.com/TECH7Fox/asterisk-hass-addons/blob/e55c7919aeb9b6301e420a59f88e68c3c8c9ef40/asterisk/rootfs/stdin.sh) script which I run as CMD? I'm not forwarding stdin to the Asterisk process, I'm handling stdin by my own. Maybe you missed this part.

Let's sort this out first before I answer the rest of your comment.

**Comment by felipecrs** [comment]
> In any case, I _could_ add a "waitfor" command to s6-overlay, that you would run as `CMD [ "waitfor", "foo" ]` and that would exit when supervised service `foo` exits, which would make the container exit - that may indeed simplify the `./finish` scripts hacks. But that will not help with stdin, so your Asterix thing wouldn't be able to use it.

I don't think this is a good idea. If `CMD ["waitfor" "foo"]` works for some user, it means `CMD ["foo.sh"]` also will, which even simplifies the container as the `foo` service no longer needs to be defined.

Except perhaps... the user wants to use some service-specific feature of s6 for this process, like collecting logs.

**Comment by skarnet** [comment]
- Ah, I get it. You need `stdin.sh` because you need to process the input, you're not sending it to Asterix directly.
- Frigate is a good example indeed: it's valid to want logging for your main service.

So here are my thoughts:

- Frigate would work with my `waitfor` command.
- Is there a specific reason why Asterix needs to be the main service in your `stdin.sh` configuration? Can't you kill `stdin.sh`, or make it exit, when you want the container to stop? From what I can tell, it should already exit when it gets an EOF on input: cannot this be the natural way of stopping the container?
- If `waitfor` had an option to also redirect stdin to the main service, would it work for you? i.e. make `stdin.sh` a supervised service, and use `CMD [ "waitfor", "-0", "stdin"]` (assuming `stdin` is the name of the service and `-0` is the redirect option)
- This may seem complicated, but be assured it's the least complicated I can make things, because s6 isn't at all suited to what you're asking, and your `critical-longrun` suggestion is just downright impossible to implement (it goes _against_ the design or a supervision system that is to keep services _up_ as much as possible).

**Comment by skarnet** [comment]
> I want the container to stop whenever Asterisk service stops.

I get that, but what is the exit condition for Asterisk? Is there a reason why it would stop naturally? Because if you're sending an `s6-svc -d` command to stop it, you could just `shutdown` the container instead; if it shuts down on some external input, where does the input come from? If it's from `stdin.sh`, you may just as well stop that one instead. My point being, since Asterix is a long-running program, you need to explicitly shut it down anyway, and there's functionally no difference between shutting it down and shutting the container down.

Anyway, I think I'll work on a option to make stdin accessible from a supervised service rather than only the CMD, so you'll be able to supervise your `stdin.sh` too.

I'll also try and find a way that doesn't involve a `waitfor` command to designate a supervised service to be the "container master". Don't expect it soon, but it's doable.

**Comment by felipecrs** [comment]
> I get that, but what is the exit condition for Asterisk? Is there a reason why it would stop naturally?

The Asterisk server is meant to never stop. It could exit on some panic, could exit on bad user configuration, etc. And from a container perspective, I want the Asterisk container to exit if the Asterisk process exits, as if it was the main process "CMD".

> if it shuts down on some external input, where does the input come from? If it's from stdin.sh, you may just as well stop that one instead.

It does not stop from input from stdin, although it's doable too. It could stop from a REST API which requests the Asterisk server to restart, for example.

But we are getting too specific to Asterisk. The point I'm trying to make is more generic than that. Something that could apply to unknown workloads (you don't have what kind of services users will supervise with s6).

> Anyway, I think I'll work on a option to make stdin accessible from a supervised service rather than only the CMD, so you'll be able to supervise your `stdin.sh` too.

Meaning I'd be able to send stdin to `stdin` service while still having `CMD ["asterisk"]` for example? That would solve the Asterisk add-on dilema, but I thought it wasn't doable.

> I'll also try and find a way that doesn't involve a `waitfor` command to designate a supervised service to be the "container master". Don't expect it soon, but it's doable.

I don't have anything against this `waitfor` idea by the way. It indeed addresses the "issue" for some of the containers I shared.

---

You don't like that `/run/s6/basedir/bin/take-down` utility idea? 😅

**Comment by felipecrs** [comment]
Actually, I agree.

If you could make stdin be forwarded to some supervised service beyond CMD, and if there was a way to mark some service as "main" (through `waitfor`, for example), it would solve all issues without needing such utility.
