### ISSUE TITLE
Question about services.d vs services folders.

### ISSUE THREAD

**Issue by cmfatih** [just-containers/s6-overlay#93]
Hi,

Sometimes I'm changing service run files and restart them with `s6-svc -u /var/run/s6/services/service-name` command. If I change a service `run`file then I have to copy the file from `/etc/services.d/service-name/run` to `/var/run/s6/services/service-name/`.

Should I remove service `down` files from both folders? or `/etc/services.d/service-name` folder is enough?

P.S. : I'm changing files after `init` command and don't want to call `init` again.

Thanks

**Comment by glerchundi** [comment]
Hi @cmfatih,

s6-svscan runs against /var/run/s6/services (check here and here) so everything you need to do in runtime should be made there.

But..., because s6-hiercopy doesn't have a follow symlinks option when copying everything into /var/run, i'm symlinking /etc/{fix-attrs.d,cont-init.d,cont-finish.d,services.d} into /var/run/s6/etc/{fix-attrs.d,cont-init.d,cont-finish.d,services.d}. So the answer now is, it doesn't matter whether you make changes in /etc/x or /var/run/s6/x, but in order to being compatible with future releases use /var/run.

Refs: https://github.com/just-containers/s6-overlay/blob/master/builder/overlay-rootfs/etc/s6/init/init-stage2#L45-L47

**Comment by cmfatih** [comment]
@glerchundi : got it, thank you so much for detailed answer :smile:

**Comment by glerchundi** [comment]
you're welcome, closing this then.
