### ISSUE TITLE
How to set user and group via fix-attrs.d file?

### ISSUE THREAD

**Issue by snc** [just-containers/s6-overlay#97]
Is it currently possible to change the user (`account`) and the group via a `fix-attrs.d` file?

I tried:

```
/usr/sbin/ssmtp false root:ssmtp 2755 0750
/etc/ssmtp true root:ssmtp 0640 0750
```

but it raises an error (but still exits with 0):

```
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 00-ssmtp: applying...
s6-envuidgid: fatal: unknown user: root:ssmtp
s6-envuidgid: fatal: unknown user: root:ssmtp
s6-envuidgid: fatal: unknown user: root:ssmtp
s6-envuidgid: fatal: unknown user: root:ssmtp
[fix-attrs.d] 00-ssmtp: exited 0.
[fix-attrs.d] done.
```

**Comment by robinroestenburg** [comment]
The user/group are set by the `fix-attrs.d` script using `s6-setuidgid`, see here https://github.com/just-containers/s6-overlay/blob/master/builder/overlay-rootfs/usr/bin/fix-attrs#L12.

The `s6-setuidgid` program takes either the user id and group id (e.g. 123:456) or the account name (e.g. root), check http://www.skarnet.org/software/s6/s6-envuidgid.html for more info.

**Comment by glerchundi** [comment]
@robinroestenburg small but high-quality community in here :-)
@snc can we consider this as solved?

**Comment by snc** [comment]
In my use case the numerical `gid` is not static and can change, so I can't really use `non-existing-account,0:100`. I've simply added chown/chmod statements to the Dockerfile and removed the `fix-attrs.d` file.

How would you change the group if you only know the name?

**Comment by glerchundi** [comment]
It's not possible right now until `s6-envuidgid` or `fix-attrs` supports this. You can ask in the supervision mailing list if it's worth or not. [`gosu`](https://github.com/tianon/gosu) seems to support your use case maybe `s6-envuidgid` could do exactly the same.

/cc @skarnet

**Comment by skarnet** [comment]
Try `s6-envuidgid -g` with the latest s6 git.

**Comment by glerchundi** [comment]
@skarnet thanks for you quick response!

Probably i'm missing something but how can we solve this issue with the `-g` option? I would expect something like `-n: if a : separator was found, try to resolve them with username:groupname first and fallback to uid:gid if they don't exist`.

I think this should solve the 99% of the common use-cases. It can behave strangely when someone writes a numeric value for username/groupname, expecting to use them as uid/gid, although it was solving resolving to the real value in /etc/{passwd,group}. But I think it's okay, because I don't think it's a common practice to have {username,groupname}s like "1" or "101".

WDYT?

**Comment by skarnet** [comment]
In fix-attrs: take a field for $user, a field for $group (or just one field $user:$group if you don't want to break compatibility, but it's more of a pain to parse), and do `s6-envuidgid $user s6-envuidgid -g $group ...` to get the wanted $UID and $GID.

**Comment by glerchundi** [comment]
i will give it a try on weekend, thanks.

**Comment by glerchundi** [comment]
@skarnet PTAL.

I've made an implementation to work with all the use-cases, but probably it can be done far better and easier (which means more maintainable).

From this:

```
foreground { s6-envuidgid ${envuidgid_opts} ${account} s6-chown -U -- ${1} }
```

To this:
```
[...]
foreground
{
  multidefine -Cd":" -- ${account} { user group }
  ifelse -- { s6-test -z ${group} }
  {
    s6-envuidgid ${envuidgid_opts} ${account}
    s6-chown -U -- ${1}
  }
  backtick -n uid
  {
    ifte { s6-envuidgid ${user} import -u UID s6-echo ${UID} } { s6-envuidgid -D${user}:0 ${user} import -u UID s6-echo ${UID} }
    foreground { redirfd -w 1 /dev/null fdmove -c 2 1 s6-test ${user} -eq ${user} }
    import -u ?
    s6-test ${?} -ne 0
  }
  import -u uid
  backtick -n gid
  {
    ifte { s6-envuidgid -g ${group} import -u GID s6-echo ${GID} } { s6-envuidgid -g -D0:${group} ${group} import -u GID s6-echo ${GID} }
    foreground { redirfd -w 1 /dev/null fdmove -c 2 1 s6-test ${group} -eq ${group} }
    import -u ?
    s6-test ${?} -ne 0
  }
  import -u gid
  s6-chown -u ${uid} -g ${gid} -- ${1}
}
[...]
```

Yes, it was a pain.

These were the use-cases I tried:

1. `account`: `/path/to/my/file false daemon 0600 0700`
2. `uid:gid`: `/path/to/my/file false 2:2 0600 0700`
3. `uid:gname`: `/path/to/my/file false 2:daemon 0600 0700`
4. `uname:gid`: `/path/to/my/file false daemon,2 0600 0700`
5. `uname:gname`: `/path/to/my/file false daemon,daemon 0600 0700`

If there exists a username with '2' its uid will be used instead of 2. Same with groupname/gid.

**Comment by skarnet** [comment]
Ew, that's ugly. Keep it for the time being - I'll try and see if I can come up with something simpler; if I cannot, I'll fiddle with `s6-envuidgid` options to make your use case easier to write.

**Comment by glerchundi** [comment]
Yep, really ugly and really hard to maintain too, I'll appreciate anything that simplifies at least a little bit. Thanks.

**Comment by skarnet** [comment]
Try `s6-envuidgid -nB ${account}` with the latest s6 git.

**Comment by glerchundi** [comment]
@skarnet first of all, THANKS :-)

It seems to work for all cases except for one, i don't know if it was done in that way deliberately but anyway, here my tests:

I used this script:

`s6-envuidgid-test`:
```
#!/usr/bin/execlineb -S1
s6-envuidgid -D 3:4 -nB ${1}
import -u UID
import -u GID
s6-echo -- ${UID} ${GID}
```

```
/ # ./s6-envuidgid-test daemon
2
/ # ./s6-envuidgid-test 2:2
2 2
/ # ./s6-envuidgid-test daemon:2
2 2
/ # ./s6-envuidgid-test 2:daemon
2 2
/ # ./s6-envuidgid-test daemon:daemon
2 2
/ # vi s6-envuidgid-test 
/ # ./s6-envuidgid-test daemon:pepito
2 4
/ # ./s6-envuidgid-test pepito:daemon
3 2
/ # ./s6-envuidgid-test 11111:11111
11111 11111
```

The very first test doesn't work as expected, at least for me. Apparently GID is not set if just account name is used.

**Comment by skarnet** [comment]
`./s6-envuidgid-test daemon` will only set UID because you only provide a UID. If you try `./s6-envuidgidtest daemon:` (with a colon), however, you're saying that a GID should be provided too, but since you're not giving one, it will default to 4.

 I don't like the asymmetry: `s6-envuidgid daemon:` will set UID and GID, but `s6-envuidgid :daemon` will only set GID. But it's the most intuitive way of doing what you want with `-B` ; if people only want UID or only want GID, they should use `-u` or `-g`.

**Comment by glerchundi** [comment]
> ./s6-envuidgid-test daemon will only set UID because you only provide a UID.

For me doing `s6-envuidgid daemon` should be the same as doing `s6-envuidgid -nB daemon`. At least that would be what I would expect. If you don't provide a colon the parameter is the account and GID should be set accordingly.

> I don't like the asymmetry: s6-envuidgid daemon: will set UID and GID, but s6-envuidgid :daemon will only set GID. Maybe I should always try and get a default UID when -B is used?

I think so, asymmetry would confuse to whoever uses it.

Anyway, and in case you don't change anything else, last git simplifies `fix-attrs` **A LOT**!

**Comment by glerchundi** [comment]
This looks weird, me answering to myself!! Add a new comment instead of modifying the one I previously posted haha. It looks like, as you're a member of `just-containers`, you've the possibility to modify anyone's comments.

> I'm inclined to change it to the latter, so that user: and :group behave the same way.

me too.

> That is the case when you don't use -B. If you want the account name, don't use options: you'll get UID, GID and GIDLIST, but you lose the ability to provide numerical fallbacks.

I'm divided here, I don't know what would the enduser expect if just the account is used (in `fix-attrs` terms of course). In any case, In order to be backward compatible both paths separation should be done.

Do you have any plan to release in the next weeks?

**Comment by skarnet** [comment]
You could for instance use `s6-envuidgid -nB` or `s6-envuidgid` depending on whether there's a `:` in the argument or not.

I will probably make a release next week.

**Comment by glerchundi** [comment]
Sorry I don't know why I closed this :\, as it's not implemented yet.

**Comment by glerchundi** [comment]
@skarnet last release changed `s6-envuidgid` behaviour breaking backward compatibility when `-Duid:gid` option is used. It seems like GID, GIDLIST are not set:

```
/ # s6-envuidgid -D2:3 nobody import -u UID s6-echo \${UID}
65534
/ # s6-envuidgid -D2:3 nobody import -u GID s6-echo \${GID}
65534
```

```
/ # s6-envuidgid -D2:3 nobody import -u UID s6-echo \${UID}
65534
/ # s6-envuidgid -D2:3 nobody import -u GID s6-echo \${GID}


```

Otherwise it seems to work as expected.

**Comment by skarnet** [comment]
Ah, damn, that's ugly. Would you like the `-D` option to perform as before? If yes, I'll have to add a way to provide a default GIDLIST too.

**Comment by glerchundi** [comment]
At least if it is possible I would like to behave in the same way it did in the last release. Otherwise it will further complicate my `fix-attrs` implementation:

Now it looks like this:
```
[...]
# get 'uid' and 'gid'
multidefine -Cd"," -- ${userentry} { account uidgid }
backtick -n envuidgid_opts
{
  backtick -n opts
  {
    ifte { s6-echo -- -D${uidgid} } { s6-echo -- -i }
    s6-test -n ${uidgid}
  }
  importas -u opts opts
  ifte { s6-echo -- ${opts} } { s6-echo -- -nB ${opts} }
  pipeline { s6-echo ${account} } s6-grep -- ":"
}
importas -u -sCd" \t" envuidgid_opts envuidgid_opts
s6-envuidgid ${envuidgid_opts} ${account}
importas -u uid UID
importas -u gid GID
[...]
```

By the way, and being the execline master&commander what do you think abount how I implemented these features?

**Comment by skarnet** [comment]
My opinion is that execline is meant to make your life simpler, not more complicated, and if you have to write pages of scripts, you're probably using the wrong tool. Tbh, if you have string manipulation like this, it's probably more efficient to call `/bin/sh -c "two lines of idiomatic shell"`, even in an execline script - and every image under the sun will have `/bin/sh` so that wouldn't exactly break the overlay independence. :-)

But nevertheless, I'm happy to see execline stress-tested this way!

I'll try and find the time this week-end or early next week to revert `s6-envuidgid -Dsomething` to the old behaviour, with acceptable and well-defined semantics.

**Comment by glerchundi** [comment]
> My opinion is that execline is meant to make your life simpler, not more complicated

Of course, and it does (easier).

> and if you have to write pages of scripts, you're probably using the wrong tool.

I agree, the long-term approach would be to create a zero-dependencies binary which follows with the idea of a "you can use this overlay in slim images like busybox, alpine or even with scratch"

> and every image under the sun will have /bin/sh so that wouldn't exactly break the overlay independence. :-)

Yes and no, they usually have. But, as instance, the `scratch` base image doesn't and it's fairly typical to use this image for example for go-based images (although I think it's not worth it).

> But nevertheless, I'm happy to see execline stress-tested this way!

And it works pretty well :)

> I'll try and find the time this week-end or early next week to revert s6-envuidgid -Dsomething to the old behaviour, with acceptable and well-defined semantics.

Don't worry, whenever you can.

**Comment by skarnet** [comment]
Please try the current s6 git and tell me if it works for you.
If you need a versioned release, I'll do one soon. If you don't, I'll wait a bit more.

**Comment by glerchundi** [comment]
> If you need a versioned release, I'll do one soon. If you don't, I'll wait a bit more.

Last time we did this kind of exchange I prepared our source to be released from a concrete git commit, and it seems to work :-) just-containers/skaware#33

thanks, it works as expected. I re-run everything again:

```
/ # ./s6-envuidgid-test daemon
2 4
/ # ./s6-envuidgid-test 2:2
2 2
/ # ./s6-envuidgid-test daemon:2
2 2
/ # ./s6-envuidgid-test 2:daemon
2 2
/ # ./s6-envuidgid-test daemon:daemon
2 2
/ # ./s6-envuidgid-test daemon:pepito
2 4
/ # ./s6-envuidgid-test pepito:daemon
3 2
/ # ./s6-envuidgid-test 11111:11111
11111 11111
/ # adduser -u 22222 2
/ # ./s6-envuidgid-test 2:daemon
22222 2
/ # ./s6-envuidgid-test daemon:2
2 22222
/ # ./s6-envuidgid-test 2:2
22222 22222
```

Also the first and conflictive one works :-)

@snc I created a new release (#121 `v1.17.1.0`) with modified `fix-attrs` binary. Please test a tell us something.

**Comment by snc** [comment]
While removing my `chown -R :ssmtp /etc/ssmtp /usr/sbin/ssmtp` line from the Dockerfile, I wonder if this syntax is supported, too? Such a case is not listed above.

Using the initial `fix-attrs.d` file, now the group is set accordingly, but it looks like the dir/file permissions are not set?

**Comment by glerchundi** [comment]
> Using the initial fix-attrs.d file, now the group is set accordingly, but it looks like the dir/file permissions are not set?

@snc sorry it was my fault, I forgot to `foreground` the very first chown statement, I already release a new version fixing it :\ (`v1.17.1.1`).

> While removing my chown -R :ssmtp /etc/ssmtp /usr/sbin/ssmtp line from the Dockerfile, I wonder if this syntax is supported, too? Such a case is not listed above.

It's supported but I don't know if it behaves like you would expect:

with fallback `uid:gid` (`-D 3:4`)
```
/ # ./s6-envuidgid-test daemon:
2 4
/ # ./s6-envuidgid-test :daemon
3 2
```

without fallback `uid:gid`
```
/ # ./s6-envuidgid-test :daemon
0 2
/ # ./s6-envuidgid-test daemon:
2 0
```

As you can see if fallback is not set, uid/gid is defaults to 0.

**Comment by snc** [comment]
OK thanks for explanation, the `chown` command would only set the group and not change the user.
The file modes are now working again :+1:

This issue can be closed then, or maybe the README should be updated before?

**Comment by glerchundi** [comment]
@snc, I'll add all the valid use cases to the README. thanks.
